Fix inline box positioning on Safari
isaacphysics/isaac-react-app pull request #1007
Opened 2024-06-24 08:39 UTC by jacbn

Fixes the issue with boxes appearing too high until they are typed in on Safari. No noticeable differences on any other browser.

2024-06-24 13:51 UTC, jsharkey13 commented
This has fixed the text box alignment within a line 🎉, however it has now broken the units box alignment with its corresponding text box 😣

2024-06-26 08:53 UTC, skyepurchase requested changes
LGTM. Just need to remove a vestigial classname that no longer has any apparent use

2024-06-26 08:53 UTC, skyepurchase commented on src/app/components/elements/inputs/InlineNumericEntryZone.tsx
> +                    "inline-input force-print h-100",
```suggestion
                    "force-print h-100",
```
`inline-input` no longer exists so can be removed

2024-06-26 08:53 UTC, skyepurchase commented on src/app/components/elements/inputs/InlineStringEntryZone.tsx
> +                "inline-input force-print",
```suggestion
                "force-print", 
```
Same as above

2024-06-26 08:56 UTC, skyepurchase approved these changes

2024-06-26 09:04 UTC, merged