Ada core and advanced tagging
isaacphysics/isaac-react-app pull request #1014
Opened 2024-07-02 16:42 UTC by skyepurchase

If a topic or concept is not on a users specification display the tag as "core" or "advanced" based on prior tagging. This prefers "core" over "advanced" and only shows "advanced" if "core" is not present.

If a user has not set their preferences every tag is displayed as "core" or "advanced". To accomodate this, if a user has not set their preferences , on Ada, they have a new "none" stage and examboard to distinguish from deliberately selected "all".

2024-07-17 07:28 UTC, mwtrew requested changes

2024-07-17 07:28 UTC, mwtrew commented on src/app/components/elements/list-groups/TopicSummaryLinks.tsx
>              .map((item, index) => {
There seems to be a bit of a mismatch between what's happening here and in Accordions - if I set my stage to `Ada` `Core`, Core topic summaries have an empty but still coloured stage label (see attached) and Core accordions have no label at all. I'm not sure which if either is desired.
<img width="1068" alt="Screenshot 2024-07-16 at 17 21 03" src="https://github.com/user-attachments/assets/4e1a3a60-1c80-45fc-80b3-0923a4ddf509">

It might be nice to factor out the common code to reduce the likelihood of differences, but perhaps not now.

2024-07-17 12:32 UTC, mwtrew approved these changes

2024-07-22 15:45 UTC, jsharkey13 commented on src/app/components/elements/inputs/UserContextAccountInput.tsx
> +            }) || [EXAM_BOARD.ADA];
The method `getFilteredExamBoardOptions` returns an array of `{label: string, value: EXAM_BOARD}` objects, but then we have this array that just contains `EXAM_BOARD.ADA` and is thus a completely different type. This isn't a new problem, but I do think we should fix it.

2024-07-22 15:46 UTC, jsharkey13 commented
I merged the Bootstrap changes into this, and I think I resolved the messy conflict correctly. However, there are type warnings in my IDE, which I think are valid and I have commented about above.

2024-07-23 11:30 UTC, merged