Physics student sign-up flow
isaacphysics/isaac-react-app pull request #1046
Opened 2024-08-12 16:28 UTC by jacbn

Adds Physics changes alongside the Ada components for the new sign-up flow (no noticeable changes should be visible on Ada).

2024-08-13 15:06 UTC, skyepurchase requested changes

2024-08-13 15:06 UTC, skyepurchase commented on src/app/components/pages/RegistrationAgeCheck.tsx
> +    const [over13, setOver13] = useState<AgePermission | undefined>(undefined);
Would be good to rename `over13` to something like `agePermission` or just `permission` to avoid potential confusion. This name change will obviously need to propagate.

2024-08-14 09:42 UTC, mwtrew commented on src/app/components/elements/inputs/SetPasswordInput.tsx
> +                required aria-describedby="invalidPassword"
Instead of the `required` prop we instead use our own `FormFeedback` everywhere for consistency, and including it breaks that - try submitting the form without filling in any fields and you'll see that `FormFeedback` no longer works.

2024-08-14 09:42 UTC, mwtrew commented on src/app/components/elements/inputs/SetPasswordInput.tsx
> +                required aria-describedby="invalidPassword"
(Sorry to jump in @skyepurchase!)

2024-08-19 09:58 UTC, mwtrew commented
Had a play around with this again and spotted a couple of minor issues:

1. You have to press tab twice to shift focus from Password to Confirm password, it must be focusing on something in between.
2. Invalid DoB (`You must be over 10 years old to create an account.`) doesn't prevent form submission as it's not a required field - maybe this is fine since the user has already confirmed they're old enough, but it's a bit weird for the message to show up.

2024-08-20 11:16 UTC, mlt47 approved these changes
I approve the changes since Matthew's last comment.

2024-08-20 11:21 UTC, skyepurchase approved these changes

2024-08-20 11:22 UTC, merged