Cloze dropdown scrolling and greying out
isaacphysics/isaac-react-app pull request #1050
Opened 2024-08-13 14:01 UTC by sjd210

Limits the size of cloze dropdown menus and adds scrollbar on vertical overflow.

Greys out previously selected options on non-replaceable cloze questions rather than removing them from the dropdown.

2024-08-13 16:19 UTC, skyepurchase requested changes
Good solution! This is a not the simplest section of the code base and I hoped the task would be more straight forward than it was.

I have a couple of suggestions for improved code style and removing unintended behaviour.

2024-08-13 16:19 UTC, skyepurchase commented on src/app/components/elements/markup/portals/InlineDropZones.tsx
> +                    return <DropdownItem key={i} style={{color:"darkgray", backgroundColor:"lightgray", pointerEvents:"none"}}>
Unfortunately `'pointerEvents': "none"` means that the item acts invisible to clicks and so the user would click through the item onto the page behind potentially interacting with a component they did not intend.

`DropdownItem`s have a `disabled` property that should do what you want here. It would also be worth checking the `active` property as it may do the graying out.

2024-08-13 16:19 UTC, skyepurchase commented on src/app/components/elements/markup/portals/InlineDropZones.tsx
> +                if (nonSelectedItemIds.includes(item.id))
After the changes I suggested for invalid items the two different `DropdownItem`s will be very similar. It would be better to conditionally set the `disabled` property based on `nonSelectedItemIds.includes(item.id)` similarly for adding the `invalid` classname using the `classNames` function.

2024-08-13 16:19 UTC, skyepurchase commented on src/app/components/elements/markup/portals/InlineDropZones.tsx
> +    const nonSelectedItemIds = nonSelectedItems.map(item => item.id);
This works perfectly fine and doesn't need to however with `line 127` you could use `dropRegionContext?.nonSelectedItems.every(nsi => nsi.id !== item.id)` which would be a bit neater with less variables

2024-08-14 08:41 UTC, sjd210 commented on src/app/components/elements/markup/portals/InlineDropZones.tsx
> +    const nonSelectedItemIds = nonSelectedItems.map(item => item.id);
Good note. I've decided that probably the easiest-to-read option here is to keep `nonSelectedItemIds` as its own variable while removing `nonSelecteditems` as it can already be directly accessed through `dropRegionContext`.

2024-08-14 09:00 UTC, sjd210 commented on src/app/components/elements/markup/portals/InlineDropZones.tsx
> +                    return <DropdownItem key={i} style={{color:"darkgray", backgroundColor:"lightgray", pointerEvents:"none"}}>
It looks like `disabled` handles both disabling clicks and graying out the items (`active` seems to be unrelated to this kind of behavior).

That said, on closer inspection it also appears that both `disabled` AND `'pointerEvents': "none"` interact poorly with the new dropdown scrolling functionality on touchscreen, so potentially the best solution is just to disable `onClick` functionality for selected options. I'm looking into this now.

2024-08-14 09:47 UTC, sjd210 commented on src/app/components/elements/markup/portals/InlineDropZones.tsx
> +                    return <DropdownItem key={i} style={{color:"darkgray", backgroundColor:"lightgray", pointerEvents:"none"}}>
I've implemented this in my latest push. This does mean that the pointer on desktop will still highlight the invalid dropdown items as clickable, but this fixes touchscreen usability. 

Realistically, I think this makes no real difference. The dropdowns only exist for `xs` screens which should all be touchscreen.

2024-08-14 14:27 UTC, skyepurchase approved these changes
Annoying that bootstrap puts `pointer-events: none` on it's disabled class!!

2024-08-14 14:27 UTC, merged