Question finder completeness filters
isaacphysics/isaac-react-app pull request #1060
Opened 2024-08-16 11:16 UTC by skyepurchase

- Improve email regex
- Implement question filtering by completion status
- Add styling based on question completion status
- Fix difficulty icon width

2024-08-22 09:40 UTC, mlt47 requested changes
The feature looks neat. There are a few comments to look at before merging.

2024-08-22 09:40 UTC, mlt47 commented on src/app/services/reactRouterExtension.ts
> +export type singleParams = {[key: string]: string | undefined};
Types are PascalCase by convention.

2024-08-22 09:40 UTC, mlt47 commented on src/app/components/elements/svg/DifficultyIcons.tsx
> -            width={`${difficultyCategoryLevels.length * (difficultyIconWidth + 2 * difficultyIconXPadding) - difficultyIconXPadding}px`}
This doesn't seem correct to me. I would have thought there should be 1 unit of padding to the left of each icon + 1 on the right? This doesn't seem like the correct formula.

2024-08-22 09:40 UTC, mlt47 commented on src/app/components/pages/QuestionFinder.tsx
> +                                        : <em>No results match your criteria</em>)
I get this response when searching with just the filter statuses on. It is not made clear to the user why we don't return anything in this case. I actually think we should also be returning results in this case.

2024-08-22 09:40 UTC, mlt47 commented on src/app/components/pages/QuestionFinder.tsx
> +        };
It might look neater for these to all be false, initially.

2024-08-22 09:40 UTC, mlt47 commented on src/app/components/pages/QuestionFinder.tsx
> +
We can get rid of the useEffect and the useState if we just have `const filteringByStatus = !(Object.values(searchStatuses).every(v => v) || Object.values(searchStatuses).every(v => !v));`

2024-08-22 10:45 UTC, skyepurchase commented on src/app/components/pages/QuestionFinder.tsx
> +                .map(e => e[0] === "incorrect" ? "tryAgain" : e[0]).join(",");
Ada wants a friendly presentation. It might be worth changing the status entry to "tryAgain".

2024-08-22 11:01 UTC, skyepurchase commented on src/app/components/elements/list-groups/ContentSummaryListGroupItem.tsx
> +    let questionIconLabel, questionIcon;
Need to be running the new backend as it has breaking changes that this requires

2024-08-22 14:47 UTC, skyepurchase commented on src/app/components/elements/svg/DifficultyIcons.tsx
> -            width={`${difficultyCategoryLevels.length * (difficultyIconWidth + 2 * difficultyIconXPadding) - difficultyIconXPadding}px`}
Will look into this in future. For now minor change to block the PR on.

2024-08-23 08:43 UTC, mlt47 commented on src/app/components/elements/svg/DifficultyIcons.tsx
> -            width={`${difficultyCategoryLevels.length * (difficultyIconWidth + 2 * difficultyIconXPadding) - difficultyIconXPadding}px`}
Agree. (It might be that there are two paddings between each icon in which case the original formula is correct but we might need some small amount of additional padding to account for borders or similar).

2024-08-23 09:34 UTC, mlt47 approved these changes
Looks good to me. I think that students will find the status search, combined with the rest of the page, very useful!

2024-08-23 09:37 UTC, merged