Improve gameboard builder table
isaacphysics/isaac-react-app pull request #1063
Opened 2024-08-20 10:48 UTC by skyepurchase

Use multiple rows for each question specification and merge the rows that do not change across specification (such as the title).

This reverts back to `findAudienceRecordsMatchingPartial` to convert the single (partial) audience view examboard into all the relevant examboards.

2024-08-21 09:00 UTC, sjd210 requested changes

2024-08-21 09:00 UTC, sjd210 commented on src/app/services/userViewingContext.ts
> +                audienceRecord[key as keyof AudienceContext]?.[0] === value);
Only checking position `0` leads to incorrectly not displaying exam boards when a valid exam board exists in a later position in the `audienceRecord` array (see picture):

![image](https://github.com/user-attachments/assets/f44845bd-1484-4250-9416-388099913263)
(The non-displayed exam boards have AQA as their first element, but it is not a filtered exam board)

---

Changing the line to `audienceRecord[key as keyof AudienceContext]?.includes(value as never)); ` seems to fix this, although you may want to look for a better `TypeScript` solution than casting as never.

2024-08-22 14:19 UTC, skyepurchase commented on src/app/services/userViewingContext.ts
> +                audienceRecord[key as keyof AudienceContext]?.[0] === value);
Ah I thought this might happen. Rather than fix this problem I have updated the tagging so that it only shows the exam-boards in the viewing contexts based on filtering. This means no weird expansion from a single exam-board (I have removed the function as it is not used anywhere and its functionality is not required).

2024-08-23 16:37 UTC, sjd210 requested changes

2024-08-23 16:37 UTC, sjd210 commented on src/app/components/elements/GameboardBuilderRow.tsx
> +            {/* Show each difficulty icon for Physics or just the first one for Ada */}
This *would* be fine if we assumed that all Ada questions have a difficulty set on their first filtered option. Unfortunately, I have found at least a few questions where this isn't the case:

![image](https://github.com/user-attachments/assets/4e1395cb-cbe2-4007-8a76-1dae3c4fc2b4)

_See [here](https://github.com/isaacphysics/ada-content/blob/710bd180ecf12dc6402bbeb54e8ed1d737eb6409/content/computer_science/data_structures_and_algorithms/data_structures/questions/struct_64.json#L133) in the `ada-content` repo - the GCSE audience doesn't have a difficulty marked (which it definitely should, and a [recent change](https://github.com/isaacphysics/isaac-content-editor/commit/94a547e662447d776a38bef645beff60557738cd) to the content editor should fix this for all future questions - perhaps we should have a script to fix this for existing questions?)._

Regardless, I advise changing to the first non-null `difficulty` from the entire question rather than just the first `difficulty` from the filtered selection.

2024-08-27 12:32 UTC, sjd210 approved these changes

2024-09-10 08:47 UTC, mlt47 approved these changes

2024-09-10 08:48 UTC, merged