Fix Ada search formatting
isaacphysics/isaac-react-app pull request #1065
Opened 2024-08-20 13:55 UTC by axlewin

2024-08-22 11:41 UTC, jacbn requested changes
Nice stuff, the search page is definitely a lot cleaner now! A couple of points before it can go in though.

2024-08-22 11:41 UTC, jacbn commented on src/app/components/elements/list-groups/ContentSummaryListGroupItem.tsx
> +            <img src="/assets/common/icons/not-started.svg" height="34px" alt={questionIconLabel}/>
`ContentSummaryListGroupItem`s are unfortunately used elsewhere (c.f. new question finder in particular) with other images that need this to be the height it is, so we can't change this here. I don't think it looks _too_ bad as is, but if you would rather have it you'd need to add this in the css somewhere under `#search-page {...} img`.

2024-08-22 11:41 UTC, jacbn commented on src/scss/cs/boards.scss
> +  min-width: 75px !important;
Two things:
1. I'm not really sure why the height is fixed here. The rows change height (particularly on mobile) and fixing it will only break it when it's not its standard height. Indeed, it is broken on [the live site](https://adacomputerscience.org/search?examBoard=all&query=arch&stage=all&types=isaacConceptPage,isaacTopicSummaryPage,page,isaacQuestionPage) too... (scroll down to Von Neumann at `md` width -- note the border-right on this component stopping after 88px). Given that it's `display: inline-block` you can actually just remove the line setting the height from the css and it should work.

2. Setting the min-width is the right thing to do, but if we do it one layer down (inside `.inner-progress-icon` we can both keep all relevant props on one element (particularly now that we don't need the height in `.question-progress-icon`), and no longer need the `!important`.

2024-08-22 11:41 UTC, jacbn commented on src/app/components/elements/list-groups/ContentSummaryListGroupItem.tsx
> +            <img src="/assets/common/icons/not-started.svg" height="34px" alt={questionIconLabel}/>
Also, just on a more general note -- if you're having to modify one component of a given type and not the others (as in this case, where you're adding a height to this one svg but not the ones nearby which do similar things) there's probably a cleaner way of doing it, e.g. through css via the parent component.

2024-08-26 10:20 UTC, mwtrew requested changes
<img width="597" alt="Screenshot 2024-08-26 at 10 58 59" src="https://github.com/user-attachments/assets/88e8865a-3d39-4f00-9848-681176981162">

Looks like [Jacob's first point here](https://github.com/isaacphysics/isaac-react-app/pull/1065#discussion_r1726889738) is still an issue - getting rid of [this CSS](https://github.com/isaacphysics/isaac-react-app/blob/master/src/scss/cs/list-groups.scss#L4) (I'm not sure why that's there either) should do it.

2024-08-27 15:23 UTC, jacbn approved these changes

2024-08-27 15:26 UTC, jsharkey13 approved these changes

2024-08-27 15:26 UTC, merged