Chemistry and nuclear text entry
isaacphysics/isaac-react-app pull request #1075
Opened 2024-08-23 15:52 UTC by skyepurchase

- Implement text entry for Chemistry questions
- Implement nuclear text entry
- Improve feedback for users

2024-09-02 14:29 UTC, sjd210 requested changes
I really liked seeing this all work together. There are just a few small front-end issues I think need solving here, but the grammar itself works perfectly!

2024-09-03 15:26 UTC, skyepurchase commented on src/app/components/content/IsaacSymbolicChemistryQuestion.tsx
> +                    The following symbols may be useful: <pre>{symbolList}</pre>
There's two ways about this:
1. Change it in Inequality to accept `\alphaparticle` rather than `alpha`
2. Change it in the front-end to convert `alpha` to `\alphaparticle`

The second is easiest, though ideally both would be in sync. There is also a case for allowing users to input `alpha`, `beta`, `n`, etc. But that will need to be done in the grammar.

2024-09-04 11:15 UTC, sjd210 commented on src/app/components/content/IsaacSymbolicChemistryQuestion.tsx
> +                                ? <UncontrolledTooltip placement="top" autohide={false} target={helpTooltipId}>
Nice examples! However I think that with the length of Nuclear answers, the overflow of an example over multiple lines makes it quite unclear when one ends and the next starts. I've got a couple different solutions in mind:

Either we can change each `<br />` to `<br className="mb-2" />` 

OR for the same effect with a more forward-thinking approach add a new className like `spacedTooltip` to `UncontrolledTooltip` 

```suggestion
                                ? <UncontrolledTooltip className="spacedTooltip" placement="top" autohide={false} target={helpTooltipId}>
```
and then in a css file (`questions.scss` should do, at the top-level due to how tooltips are handled): 
``` 
.spacedTooltip br {
  margin-bottom: 0.5rem;
}
```

2024-09-04 11:22 UTC, sjd210 commented on src/app/components/content/IsaacSymbolicChemistryQuestion.tsx
> +                                ? <UncontrolledTooltip placement="top" autohide={false} target={helpTooltipId}>
The Chemistry tooltip below, and probably even the Symbolic Maths [tooltip](https://github.com/isaacphysics/isaac-react-app/blob/98cbab5920b7976f7021c3470121d9cbc716ce73/src/app/components/content/IsaacSymbolicQuestion.tsx#L243C1-L243C25) could probably also do with this same `spacedTooltip` treatment, as they also have examples going over multiple lines - although just 2 lines instead of the 3 here.

(I'd also then remove the extra floating `<br />`s either side of the examples - otherwise it's taking up too much space)

2024-09-06 10:26 UTC, skyepurchase commented on src/app/components/content/IsaacSymbolicChemistryQuestion.tsx
> +                                ? <UncontrolledTooltip placement="top" autohide={false} target={helpTooltipId}>
I think the maths tooltip is okay for now. If people get annoyed at the inconsistency then we can change it.

When this is merged I will also update the symbol help accordion `/solving_problems#symbolic_text` so that there is a more in depth symbol list for students.

2024-09-06 12:42 UTC, sjd210 approved these changes

2024-09-06 12:42 UTC, sjd210 commented on src/app/components/content/IsaacSymbolicChemistryQuestion.tsx
> +                                    <br />
As one final nit, I'd also remove this other hanging `<br />` as you did with the bottom ones (You don't have one on the Nuclear tooltip so there's no problem there). 

```suggestion

```
#  
After that, please do merge both PRs. I think we've had enough back-and-forth.

2024-09-06 12:46 UTC, merged