Resolve question finder default context race conditions
isaacphysics/isaac-react-app pull request #1131
Opened 2024-09-17 15:37 UTC by sjd210

2024-09-24 11:23 UTC, mlt47 requested changes
It's good that you've found a solution.
What we are aiming for is to set the filter options whenever the user, or maybe its user context, changes. Rather than adding an extra useState to get around the problem, do we know why that intended behaviour is not being achieved by the populateFromUserContext useEffect?

2024-09-26 11:21 UTC, sjd210 commented
> Rather than adding an extra useState to get around the problem, do we know why that intended behaviour is not being achieved by the populateFromUserContext useEffect? Happy to chat through this as it is quite a tricky bit of code!

@mlt47 Digging a little bit deeper, I've found that the crux of the issue seems to be `setPopulatedUserContext` updating at the wrong times. An empty array is truthy, so `userContext.stage` and `userContext.examBoard` can update it to a populated user context state without being the correctly populated values (which is why the extra `searchAndUpdateURL()` I added was needed as a workaround in the previous solution above).

It seems with some quick testing like it can be solved fairly simply by separating `setPopulatedUserContext` into its own `useEffect` with dependencies on the actual search terms (with no need for the extra useState or other work I've done here), but I'll have to experiment with how this works in different contexts to confirm this.

2024-09-26 11:31 UTC, sjd210 commented on src/app/components/pages/QuestionFinder.tsx
> +            if (userContextDefault && !userContext.hasDefaultPreferences) {
Hrm, you're absolutely right. Not sure how that slipped through my testing (although it was mostly on Ada). 

Either way, I shouldn't need to use this property in my next planned solution so shouldn't be an issue.

2024-09-27 08:34 UTC, sjd210 commented
This now boiled down to two main changes: 
**1 - Changing the check for an array of pre-existing filters (as obtained from the URL parameters) into a check for the existence of those URL parameters directly.**

This is needed so an initial 'default' user state doesn't take precedence over the real user context, but URL parameters do in order to allow the page to be refreshed/copied/etc.

**2 - Making the `searchAndUpdateURL()` `useEffect` have the search parameters as dependencies so it continues to be checked later during the loading phase, conditional on the search parameters matching those from user context.**

This is needed so `searchAndUpdateURL()` is not called early due to `userContext` being loaded in without React finishing processing the `setStages` and `setExamBoards` functions. We know the `set...` functions have finished when the parameters successfully match.

2024-10-08 16:35 UTC, sjd210 commented
@mlt47 I think your change makes a lot of sense. Only once a `user` object is instantiated will they will be logged in, at which point the object is also instantiated enough to include a `registeredContext`. It works very simply and cleanly *most of the time*.

However, I think this solution fails to cover some of the edge cases:
- Most notably, currently a logged out user on Ada will have default preferences applied on page-load, so make a search for all "Ada" Exam Board tagged items (which is all items). This disabled that page load search.
Physics doesn't have any default logged-out search parameters, so it doesn't change anything there (unless we want to specifically add a set now).

- Also somewhat notably, if a user has URL parameters other than `examBoards` and `stages` set, their blank `examBoards`/`stages` filters will be overwritten by their preferred ones on reload. We should probably make `filtersHaveNotBeenSpecifiedByQueryParams` check for the existence of *any* URL parameters. My solution had this same problem, but I've just noticed it here.

- Not much of an issue but for the sake of keeping record, a user can have no registered preferred stage context on Physics if they keep ignoring the modal to add one - and therefore will have nothing show up on loading the page. I think this is probably correct unless we do decide to add default Physics search parameters, in which case they should probably also be applied in this case.

- On a similar-ish note, if a Physics user has "All stages" set as their preferred Stage, the parameter "all" will be automatically set. This makes little practical difference to the searching as no questions are tagged with "all", but it adds an invisible count to the Stage filter and appears in the URL. 
I feel that either we should set it as a filter that actually does search for all questions (similar to the "Ada" exam board on Ada) ((which might also be suitable for if we want the default Physics search parameters I've been mentioning)) OR simply disallow it from the filters.

2024-10-09 09:56 UTC, sjd210 commented on src/app/components/pages/QuestionFinder.tsx
> +            const filtersHaveNotBeenSpecifiedByQueryParams = !params.stages && !params.examBoards;
I think this is the only blocking change. Anything else like removing the meaningless "all" tag can be made into its own card, since I think we're deciding that having no filters applied when logged out is fine. 

```suggestion
            const filtersHaveNotBeenSpecifiedByQueryParams = Object.keys(params).every(param => !["stage","examBoard"].includes(param) ? !params[param] : true);
```

There are probably other ways to handle this line, but this seems clean to me.

2024-10-28 16:25 UTC, mlt47 commented
Thanks for thinking through the edge cases, @sjd210.

> * Most notably, currently a logged out user on Ada will have default preferences applied on page-load, so make a search for all "Ada" Exam Board tagged items (which is all items). This disabled that page load search.
>   Physics doesn't have any default logged-out search parameters, so it doesn't change anything there (unless we want to specifically add a set now).
>   **[James said that we should probably just have nothing for both page loads, in which case this is fine]**

Yes, we don't want to start off with a default search. Ada is not an actual exam board so its auto selection is, in a way, always incorrect for the user!


> * Also somewhat notably, if a user has URL parameters other than `examBoards` and `stages` set, their blank `examBoards`/`stages` filters will be overwritten by their preferred ones on reload.
>   e.g. `Difficulty: P1, ExamBoard: {}, Stage: {} -> Difficulty: P1, ExamBoard: AQA, Stage: GCSE`
>   We should probably make `filtersHaveNotBeenSpecifiedByQueryParams` check for the existence of _any_ URL search parameters. My solution also had this same problem, but I've just noticed it here.

This is a very good point. We should only use account exam board and stage preference when no other filter's params are present in the URL. (We should disregard other URL params).


> * Not much of an issue but for the sake of keeping record, a user can have no registered preferred stage context on Physics if they keep ignoring the modal to add one - and therefore will have nothing show up on loading the page. I think this is probably correct unless we did decide to add default Physics search parameters, in which case they should probably also be applied in this case.

We don't want a default Physics nor Ada search so this is fine.


> * On a similar-ish note for a problem that's _mostly_ pre-existing but is highlighted here, if a Physics user has "All stages" set as their preferred Stage, the meaningless parameter "all" will be automatically set. This makes little practical difference to the searching as no questions are tagged with "all", but it adds an invisible count to the Stage filter and appears in the URL.
>   I feel that either we should set "all" as a filter that actually does search for all questions (similar to the "Ada" exam board on Ada) OR simply disallow it from the filters. (This can be its own card)

We are likely to be getting rid of the All option in the next few releases, so that will solve this problem!

2024-10-29 09:30 UTC, mlt47 approved these changes

2024-10-29 09:48 UTC, merged