Fix Teacher Connections' fixed width container problems
isaacphysics/isaac-react-app pull request #1178
Opened 2024-10-08 16:22 UTC by jacbn

2024-10-09 13:51 UTC, sjd210 requested changes

2024-10-09 13:51 UTC, sjd210 commented on src/scss/common/my-account.scss
> +
This is ideal spacing for the "Leave" button with a tooltip icon on Isaac, but on Ada the font size is different and we don't have this tooltip so it leaves an awkward gap at the end. We should probably do something along these lines:

```suggestion
  .isaac-connections-fixed-length-container {
    max-width: calc(100% - 91.8px);
  }
  
  .ada-connections-fixed-length-container {
    max-width: calc(100% - 60px);
  }
```

(with a corresponding `classNames` change in the .tsx)

2024-10-09 13:51 UTC, sjd210 commented on src/scss/common/my-account.scss
> +
On a similar note now that we have it, I would also add `connections-fixed-length-container` to lines [214](https://github.com/isaacphysics/isaac-react-app/blob/b3bf58207a03f18bc5257459aeb014b68e8f458b/src/app/components/elements/panels/TeacherConnections.tsx#L214) and [268](https://github.com/isaacphysics/isaac-react-app/blob/b3bf58207a03f18bc5257459aeb014b68e8f458b/src/app/components/elements/panels/TeacherConnections.tsx#L268) (although for Ada, we will again need another separate adjustment for its size). It's a less common problem than a group with multiple teachers, but students with particularly long names cause similar problems currently.

(From my testing, adding it directly to the `<span>` class alongside `connections-fixed-length-text` does the job with the different structure of that component).

2024-10-11 09:11 UTC, jacbn commented on src/scss/common/my-account.scss
> +
We tend to do the CSS changes with different .scss files (in /phy and /cs), but the idea is the same. I also was a bit unsure putting `-container` and `-text` on the same component was the right thing to do (even if it worked!) as the `max-width` lines were intended to be nested together, so I've cleaned that up a bit by making an actual container component.

2024-10-11 10:38 UTC, sjd210 commented on src/scss/common/my-account.scss
> +
Of course - I promise I did know this! Regardless, I prefer this restructure of the container and everything now works well.

2024-10-11 10:47 UTC, sjd210 approved these changes
Another vaguely-related change I noticed and would like while we're touching this code anyway, but as long as you're happy with that then this can just be merged.

2024-10-11 10:47 UTC, sjd210 commented on src/scss/phy/my-account.scss
> +
Nothing up with what you've done, but if we're fixing alignments here anyway then the icon in the header box on Physics has been offset and annoying me, so we might as well get this in at the same time.

```suggestion

.connect-list {
  .connect-list-header {
    .icon-person-active {
      margin-top: 7px;
    }
  
    h4 {
      padding: 0rem 1rem;
    }
  }
}

```

2024-10-16 16:01 UTC, merged