Distinguish Practice Tests
isaacphysics/isaac-react-app pull request #1229
Opened 2024-11-19 14:39 UTC by jacbn

- Splits the listing of available practice tests into its own page, `/practice_tests`, accessible via the Learn nav;
- Creates a new default table view for `/tests` (though the original card view is still accessible), which displays the title, assigner and relevant dates;
- Splits assigned tests from practice tests into separate tabs at the topmost level of `/tests`; further filtering inside these categories (for started, not yet started, overdue and completed) can be achieved via the filters menu

2024-11-20 15:21 UTC, axlewin requested changes

2024-11-20 15:21 UTC, axlewin commented on src/app/components/pages/quizzes/MyQuizzes.tsx
> +    </span>;
This link appears on both sites, but `/practice_tests` doesn't exist on Ada.

I also like the distinction between "no tests at all" and "no filtered tests" as in `emptyAssignedMessage`, but a nested conditional here probably isn't the best solution.

```suggestion
        const emptyPracticeMessage = <span className="text-muted">{isPhy
        ? !freeAttempts || freeAttempts.length === 0
            ? <>You have no practice tests in progress. Take some new tests <Link to="/practice_tests">here</Link>!</>
            : <>No practice tests match your filters. Take some new tests <Link to="/practice_tests">here</Link>!</>
        : !freeAttempts || freeAttempts.length === 0
            ? <>You have no practice tests in progress.</>
            : <>No practice tests match your filters.</>
    }</span>;
```

2024-11-20 15:21 UTC, axlewin commented on src/app/components/pages/quizzes/PracticeQuizzes.tsx
> +                <h3>Available</h3>
This heading was added to split the page up when we moved in progress & available practice tests under the same tab. Now that they're separated again, do we still need it?

2024-11-20 17:27 UTC, jacbn commented on src/app/components/pages/quizzes/MyQuizzes.tsx
> +    </span>;
Ah, it is supposed to exist on Ada. That simplifies the conditional enough that it feels nice. I'm also inclined to only have the link on if there are no tests at all, as if you're using the filters you're there to find an existing test, not take a new one.

2024-11-21 16:02 UTC, axlewin commented on src/app/components/pages/quizzes/PracticeQuizzes.tsx
> +                                    <span>Preview</span>
When viewing this page as a teacher, the option to preview a test disappears completely below `md` - there could be an "Actions" dropdown as is used for small screens on Set Tests?

(This isn't a new issue though, so not critical for merging this).

2024-11-21 16:17 UTC, axlewin commented on src/app/components/pages/quizzes/MyQuizzes.tsx
> +                    <span className={"text-nowrap"}>Filter by assigner</span>
This filter is available for practice tests, which don't have assigners - is this intentional to keep everything aligned? Would greying it out be an option?

2024-11-22 15:49 UTC, jacbn commented on src/app/components/pages/quizzes/PracticeQuizzes.tsx
> +                                    <span>Preview</span>
I believe there's a plan to add filtering to tests pretty soon, which will involve overhauling it a bit; let's wait until then.

2024-11-22 15:59 UTC, jacbn commented on src/app/components/pages/quizzes/MyQuizzes.tsx
> +                    <span className={"text-nowrap"}>Filter by assigner</span>
Greying it out would probably best, to keep the page flow the same when switching tabs. There's also the problem of what to do about the `Not started` and `Expired` states in the state filter which are invalid states for practice tests, so will never do anything. If we switch from assigned tests to practice tests with these filters set, should we remove them? Grey them out? If we do remove them, should they return if we switch back to the assigned tests tab?

I don't think there's an easy answer, and it would be nice to get the team's feedback once they have had a play around. I've made a card so we can have this discussion separately and push this through for now.

2024-11-22 16:01 UTC, axlewin approved these changes

2024-11-22 16:01 UTC, merged