Link to teacher emails from teacher features
isaacphysics/isaac-react-app pull request #1231
Opened 2024-11-21 15:23 UTC by axlewin

2024-11-22 16:18 UTC, jsharkey13 requested changes

2024-11-22 16:18 UTC, jsharkey13 commented on src/app/components/pages/TeacherFeatures.tsx
> +                <IsaacCard doc={{ clickUrl: isTeacherOrAbove(user)  ? "/teacher_emails" : "/pages/contact_us_teacher",
Jacob is right, you don't need the conditional here. But only because there's an easier way to implement the _route_ that will give you the conditional redirect for free.

2024-11-22 16:18 UTC, jsharkey13 commented on src/app/components/site/phy/RoutesPhy.tsx
> +    <TrackedRoute key={key++} exact path="/teacher_emails" component={TeacherEmails}/>,
Instead of making a new component and making a new route like this, you could instead add it to the `Teacher Pages` bit below using `<StaticPageRoute>` like the mentoring pages.

I would also like it if we could force the fragment ID to be `teacher_emails_frag` so that it is more unique. Then the `pageId` you need for the route would be `fragments/teacher_emails_frag`.

2024-11-25 11:30 UTC, jacbn approved these changes

2024-11-25 11:32 UTC, jsharkey13 approved these changes

2024-11-25 11:33 UTC, merged