Add the isaac card content type in the design of the menu card.
isaacphysics/isaac-react-app pull request #286
Opened 2020-08-21 10:14 UTC by Scratchcat1

Adds a menu card replacement which supports card decks and groups.

Test page is at `/pages/_test_card_deck`.

2020-08-24 14:50 UTC, Morpheu5 approved these changes

2020-09-03 15:59 UTC, mlt47 requested changes
This looks good so far.
We need to add a card deck object too for these content defined cards.

2020-09-09 09:08 UTC, Morpheu5 approved these changes
Looks OK to me.

2020-09-09 09:08 UTC, Morpheu5 commented on src/app/components/content/IsaacCard.tsx
> +import * as ApiTypes from "../../../IsaacApiTypes";
It's not particularly bad, but let's try to only import what we need. It help keeping things legible.

2020-09-09 09:08 UTC, Morpheu5 commented on src/app/components/content/IsaacCardDeck.tsx
> +import * as ApiTypes from "../../../IsaacApiTypes";
Same as above.

2020-09-15 13:21 UTC, mlt47 requested changes
Looks good. Have a think about how multiple card-deck rows should be presented to the user and the content editor.

2020-09-15 13:21 UTC, mlt47 commented on src/app/components/content/IsaacCardDeck.tsx
> +    return <div className={"card-deck isaac-cards-body " + className}>
In the case that the class name is left empty (as when a card deck is defined in the content) this div will receive an extra class "undefined".

Have you thought about how you would want content defined pages to show multiple rows of card decks? At the moment there would not be any gaps between each row which is probably not what we would want.
There are various ways around this -  you could add a css rule for .card-deck, add a css rule for .card-deck + .card-deck, give this component's className a default value of "mb-3", add a className propery to the card deck content object, or maybe it should be the card that has the margin?
What would be your suggestion?

2020-09-15 13:21 UTC, mlt47 commented on src/app/components/content/IsaacCardDeck.tsx
> +    return <div className={"card-deck isaac-cards-body " + className}>
I've just noticed that bootstrap also has a .card-columns option for a Pinterest style card layout.
We don't need to do it now as we don't have a use case for it, but how would you suggest we accommodate that option if the content team were to request it?

2020-09-15 13:46 UTC, Scratchcat1 commented on src/app/components/content/IsaacCardDeck.tsx
> +    return <div className={"card-deck isaac-cards-body " + className}>
`.card-deck + .card-deck` seems the best solution. We don't need to add any logic to detect if there are two consecutive card decks and the styling is only applied when required.

2020-09-15 13:50 UTC, Scratchcat1 commented on src/app/components/content/IsaacCardDeck.tsx
> +    return <div className={"card-deck isaac-cards-body " + className}>
Since they both operate on a list of cards it would be a waste to define `IsaacCardColumns`. Adding a flag (or enum/string to also support card groups) would be more flexible.

2020-09-16 15:49 UTC, mlt47 commented on src/app/components/content/IsaacCardDeck.tsx
> +    return <div className={"card-deck isaac-cards-body " + className}>
Seems a fine solution to me for now.

2020-09-16 15:49 UTC, mlt47 approved these changes

2020-09-17 13:34 UTC, merged