Clean up available symbols so we don't end up with stuff like [''] which breaks menu generation
isaacphysics/isaac-react-app pull request #295
Opened 2020-09-03 16:48 UTC by Morpheu5

2020-09-04 08:23 UTC, jsharkey13 requested changes

2020-09-04 08:23 UTC, jsharkey13 commented on src/app/components/elements/modals/InequalityModal.tsx
> +debugger;
Whilst I personally think millions of debugger statements through the code are a good way to annoy anyone trying to use DevTools - we don't want this here!

2020-09-04 10:31 UTC, Morpheu5 commented on src/app/components/elements/modals/InequalityModal.tsx
> +debugger;
🤦

2020-09-07 11:13 UTC, jsharkey13 approved these changes

2020-09-07 11:13 UTC, merged