Use all the tags in /glossary topic filter
isaacphysics/isaac-react-app pull request #315
Opened 2020-10-05 14:47 UTC by Morpheu5

Previously, the topic filter only showed the topics associated to the terms currently showing, and that was wrong.

This also fixes the case issue by using the actual tag names instead of startcasing their IDs.

Certain topic tags can have parentheses in their names, so this avoids stufflike

> (Used in: GUIs (OCR))

2020-11-10 11:18 UTC, mlt47 requested changes
This is sensible and seems to be simplifying the code which is always good!
I have made two small suggestions, would be happy to hear your view.

2020-11-10 11:18 UTC, mlt47 commented on src/app/components/pages/Glossary.tsx
> +
I would be tempted to move this into the IsaacGlossaryTerm component then you can remove its `tags` prop.

2020-11-10 11:18 UTC, mlt47 commented on src/app/components/pages/Glossary.tsx
>                              </Dropdown>}
I would express a slight preference for react-select over reactstrap's Dropdown. Dropdown looks a little clunky, particularly on mobile. React-select does not need to be multi-value (to keep the current filtering logic) and you then get the optional autocomplete from typing in the field.
I'm not sure if we would then prefer to add the fields groupings like we have on the teacher gameboard builder, if they are scanning the long list to find a topic it would probably help.

2020-11-17 10:16 UTC, mlt47 requested changes
A few more small suggestions/questions to consider before merging.

2020-11-17 10:16 UTC, mlt47 commented on src/app/components/pages/Glossary.tsx
>          if (searchText === '') {
Did you consider doing the exam board filtering here as well as in the Glossary Term component? I guess it always needs to be done in the glossary term component as that is not just used on the Glossary page. The only advantage of also doing it here would be to make the alphabet selector reflect the exam board filter. Won't be noticeable for most cases but would be if there was a Z term with only an entry for AQA, for example.

2020-11-17 11:16 UTC, Morpheu5 commented on src/app/components/pages/Glossary.tsx
>          if (searchText === '') {
Been meaning to do that and then forgot. Thanks.

2020-11-17 11:35 UTC, Morpheu5 commented on src/app/components/pages/Glossary.tsx
>                          <Col className="mt-3 mt-md-0">
We could probably do away with the alphabet but I can see how the search and exam board filters might be desirable. Trouble is, I don't know why they aren't showing up.

2020-11-18 11:49 UTC, mlt47 approved these changes
Looks good.

I would consider moving examBoard from being a property of Glossary Terms to being recorded as a tag, as that is what we do with all other content which is exam board specific. It would also make things easier in the case that we were to support a third exam board. The logic would not need to change if userExamboard in ["aqa", "wjec"] but not "ocr" for example, where as currently you are using userExamboard == "" or undefined to mean available to all.

2020-11-18 11:50 UTC, merged