Feature/gameboard filter query params
isaacphysics/isaac-react-app pull request #326
Opened 2020-10-29 10:19 UTC by mlt47

2020-11-03 11:18 UTC, bh412 commented on src/app/components/pages/GameboardFilter.tsx
> +    if (levels) {
I think this bit needs looking over, for the issue I raised on slack, otherwise it seems to work well!

2020-11-03 11:18 UTC, bh412 requested changes
Works well aside from the issue raised on slack, when rectified it will be good to go

2020-11-03 11:23 UTC, mlt47 commented on src/app/components/pages/GameboardFilter.tsx
> +    if (levels) {
Yes, well spotted. Line 47 also needs a length comparison, clearly!

2020-11-17 11:20 UTC, bh412 approved these changes
The changes add the functionality we want and fix the levels in url bug

2020-11-17 16:25 UTC, merged