Improvement/user my progress
isaacphysics/isaac-react-app pull request #349
Opened 2021-02-05 10:01 UTC by bh412

- Separate progress actions out to getMyProgress and getUserProgress.
- Separate redux states for myProgress and userProgress.
- Stops updating userSnapshot on webSocket message for userProgress reducer, stopping viewed user's streak updating to viewer's.
- Hides daily streak if 0.
- Leaves achievements alone on progress page, would only potentially affect admins viewing teachers progress, would see their own achievements.
- Still shows the teacher/admin/progress viewer's streak in the header as a separate thing, could be confusing, hopefully it makes sense to them though.

2021-02-15 14:32 UTC, mlt47 requested changes
Seems to work correctly but there is a small change request for consistency

2021-02-15 14:32 UTC, mlt47 commented on src/app/components/pages/MyProgress.tsx
> +    const viewedProgress = (!viewingOwnData && isTeacher(user)) ? userProgress : myProgress;
I think I prefer `progress` over `viewedProgress`

2021-02-15 14:32 UTC, mlt47 commented on src/app/components/pages/MyProgress.tsx
>      const answeredQuestionsByDate = useSelector((state: AppState) => state?.answeredQuestionsByDate);
This has the same problem as myProgress/userProgress they should be separate redux states to avoid accidental confusion between the states. This is less likely to happen here but seeing as we've separated one, it would be confusing to not separate the other.

2021-02-17 13:05 UTC, mlt47 commented on src/app/components/pages/MyProgress.tsx
>      const answeredQuestionsByDate = useSelector((state: AppState) => state?.answeredQuestionsByDate);
Sorry, this comment was not clear as to what line I was referring to! I meant the answeredQuestionsByDate should be split as that shows either your one or the student's one.

achievements actually don't need to be split this way because achievements, by design, are only shown if you are viewing your own progress (and we shouldn't request it if we're not showing it).

2021-02-17 15:28 UTC, bh412 commented on src/app/components/pages/MyProgress.tsx
>      const answeredQuestionsByDate = useSelector((state: AppState) => state?.answeredQuestionsByDate);
My bad! Now altered to separate out [my/user]AnsweredQuestionsByDate mirroring [my/user]Progress

2021-02-17 17:21 UTC, mlt47 approved these changes
Great, thanks for those changes and sorry for the confusion!

2021-02-17 17:21 UTC, merged