Redesign the "My Assignments" quick view
isaacphysics/isaac-react-app pull request #350
Opened 2021-02-09 10:34 UTC by Morpheu5

- Re-designed presentation
- Added notes
- Added group name

2021-02-16 10:39 UTC, bh412 reviewed
Notes not being sent needs addressing, and some general formatting for the set assignment and viewing your assignments

2021-02-16 10:39 UTC, bh412 commented on src/app/components/pages/SetAssignments.tsx
> +    const [assignmentNotes, setAssignmentNotes] = useState<string>();
This doesn't appear to then be used anywhere, the notes aren't sent off in the request

2021-02-16 10:39 UTC, bh412 commented on src/app/components/pages/SetAssignments.tsx
> +            <Input type="textarea"
This needs to be wiped when an assignment is set, like the group name, so it isn't confusing

2021-02-16 10:39 UTC, bh412 commented on src/app/components/elements/Assignments.tsx
> +                        {isDefined(topics) && topics.length > 0 && <p className="mb-0"><strong>{topics.length === 1 ? "Topic" : "Topics"}:</strong> {topics.join(", ")}</p>}
This takes up multiple lines with many topics, maybe it should be curtailed

2021-02-16 10:42 UTC, bh412 commented on src/app/components/elements/Assignments.tsx
> +                        {isDefined(assignment.groupName) &&
Doesn't appear to be returned

2021-02-16 10:43 UTC, bh412 requested changes
Needs some work on setting the notes, and checking the expected gameboard details/ names are returned as expected

2021-02-16 14:47 UTC, Morpheu5 commented on src/app/components/pages/SetAssignments.tsx
> +    const [assignmentNotes, setAssignmentNotes] = useState<string>();
Fixed.

2021-02-16 14:51 UTC, Morpheu5 commented on src/app/components/pages/SetAssignments.tsx
> +            <Input type="textarea"
Done.

2021-02-16 14:51 UTC, Morpheu5 commented on src/app/components/elements/Assignments.tsx
> +                        {isDefined(topics) && topics.length > 0 && <p className="mb-0"><strong>{topics.length === 1 ? "Topic" : "Topics"}:</strong> {topics.join(", ")}</p>}
Ask in meeting?

2021-02-16 14:52 UTC, Morpheu5 commented on src/app/components/elements/Assignments.tsx
> +                        {isDefined(assignment.groupName) &&
Can't reproduce (see API)

2021-03-18 17:10 UTC, jsharkey13 reviewed
This looks ok, although some of the funky mapping stuff is hard to comprehend!

Are the CS team ok with these changes; I notice they apply to both sites? I guess they didn't choose what is currently there but inherited it from physics, so I doubt there will be objections, but it's good to check.

2021-03-18 17:10 UTC, jsharkey13 commented on src/app/components/elements/Assignments.tsx
> +                        {isDefined(topics) && topics.length > 0 && <p className="mb-0"><strong>{topics.length === 1 ? "Topic" : "Topics"}:</strong> {topics.join(", ")}</p>}
Did this get addressed by the content team? What about the CS team? 
With 10 questions, it can get really long especially on mobile!

2021-04-07 08:05 UTC, jsharkey13 approved these changes

2021-04-07 08:05 UTC, merged