Toggle button for question reminder in Inequality
isaacphysics/isaac-react-app pull request #353
Opened 2021-02-15 14:14 UTC by Morpheu5

This adds a way of hiding the question reminder in Inequality which sometimes can block out the actual editor.

Fair warning: `pointer-events` is an evil CSS property that can interfere with browser mouse events.

2021-02-22 10:05 UTC, bh412 requested changes
On mobile screens the question is even bigger now with the button within it, and when it's 'hidden' the button and full width grey box is still there. Would it be possible to move the show/hide button out to a hexagon, like the 'centre' button and fully hide the grey question reminder box when 'hidden'. 
I'm also worried about the comment on the PR, you say it sometimes hides the full equation editor?

2021-02-22 10:05 UTC, bh412 commented on src/scss/common/inequality-modal.scss
> +        text-align: justify;
This PR seems to move the text to be left aligned, maths stays central though

2021-02-22 10:05 UTC, bh412 commented on src/scss/common/inequality-modal.scss
> +        .reminder-toggle {
Slightly worried that this doesn't achieve what it's trying to address. The box is still visible on small screens

2021-02-22 10:27 UTC, Morpheu5 commented on src/scss/common/inequality-modal.scss
> +        .reminder-toggle {
Yeah, the alternative is to have an extra hexagonal button. I might do that if I can't move the grey box enough out of the way without removing it entirely.

2021-02-22 10:28 UTC, Morpheu5 commented on src/scss/common/inequality-modal.scss
> +        text-align: justify;
The question linked in the card is horrendously long and it looks much better when justified. Math is always centred when on a line of its own.

2021-02-22 10:31 UTC, bh412 commented on src/scss/common/inequality-modal.scss
> +        text-align: justify;
Ok - felt I should flag and make sure it's a conscious decision as it changes behaviour from current

2021-02-22 10:32 UTC, bh412 commented on src/scss/common/inequality-modal.scss
> +        .reminder-toggle {
Not ideal but I'm not sure how to get around the grey box issue, having just the current button with no grey box around would also look very odd

2021-02-23 14:18 UTC, Morpheu5 commented on src/scss/common/inequality-modal.scss
> +        .reminder-toggle {
I fixed this by adding an extra button.

2021-02-23 16:47 UTC, bh412 approved these changes
Works as intended now and hides question box

2021-02-23 16:47 UTC, merged