Add Boolean logic notation preference to My account page
isaacphysics/isaac-react-app pull request #425
Opened 2021-08-09 16:46 UTC by chrisjpurdy

Backend change [here](https://github.com/isaacphysics/isaac-api/pull/375).

This adds an option on the "My account" page to change how Boolean logic is displayed - either using engineering, maths, or exam board specific notation.

The choice is stored as a map from each option to a Boolean value. In the case of multiple `true` values, the option occurring last (in the order they are listed above) is selected. I also added a `userPreferences` selector to neaten things a bit.

I'm wondering if line 161 in `UserDetails.tsx` gets run more times than needed, and if so whether it matters/could be changed?

2021-08-09 17:27 UTC, chrisjpurdy commented
Still need to add beta feature flag

2021-08-10 08:52 UTC, mlt47 requested changes
Some small suggestions, but good work

2021-08-10 08:52 UTC, mlt47 commented on src/app/components/pages/MyAccount.tsx
> +            .reduce((acc, key) => acc[key as keyof BooleanNotation] ? acc : {...acc, [key]: false}, newBooleanNotation);
I suppose a constant could be re-used with everything set to false (as long as you're careful not to mutate it :) )

2021-08-10 08:52 UTC, mlt47 commented on src/app/components/elements/panels/UserDetails.tsx
> +                        <option value={"ENG"}>And (&middot;) Or (+) Not (bar)</option>
You could use a string enum for the possible options, this will allow you to iterate over it and make sure that we update all places in the future if we add an option or change a value - particularly handy with common strings like "math" which I imagine pops up all over ourcodebase!

2021-08-10 08:52 UTC, mlt47 commented on src/app/components/elements/LaTeX.tsx
> +export function katexify(html: string, user: PotentialUser | null, examBoard: EXAM_BOARD | null, booleanNotation : BooleanNotation | null,  screenReaderHoverText: boolean, figureNumbers: FigureNumber
As this function now has a lot of arguments it might make sense to start to think about alternatives. A custom hook that looks a little like `useKatex(markdown: string): string` and then calls the other hooks inside it is an option. This does require more testing boilerplate though and, as this is one of the few functions which is reasonably well tested in the front-end, it's probably not worth making the change now unless you're particularly interested in figuring out how best to test custom hooks :)

2021-08-10 08:52 UTC, mlt47 commented on src/app/services/validation.ts
> +        (SITE_SUBJECT !== SITE.CS || (userPreferences.BETA_FEATURE?.BOOLEAN_NOTATION === null || validateBooleanNotation(userPreferences.BOOLEAN_NOTATION)));
The method allRequiredInformationIsPresent(...) is also used for deciding whether or not to display a modal to the user on sign in. This was necesary as we allow for registration via Google but we have other required fields that they need to be set. As we have already created the account at that point we just show them a modal to ask them to set it quite regularly until they do. The trouble is there is no way to select the boolean notation option in that modal yet so you'll need to add that :)
Going to dev tools > application > local storage will allow you to delete requiredModalShownTime to see it again without needing to wait the required time!
Also I see that modal even when I don't have BOOLEAN NOTATION as a beta feature on my account so worth double checking that works as you'd expect.

2021-08-10 11:30 UTC, chrisjpurdy commented on src/app/components/pages/MyAccount.tsx
> +            .reduce((acc, key) => acc[key as keyof BooleanNotation] ? acc : {...acc, [key]: false}, newBooleanNotation);
Good point!

2021-08-10 13:04 UTC, chrisjpurdy commented on src/app/components/elements/LaTeX.tsx
> +export function katexify(html: string, user: PotentialUser | null, examBoard: EXAM_BOARD | null, booleanNotation : BooleanNotation | null,  screenReaderHoverText: boolean, figureNumbers: FigureNumber
I think I'll keep it as is for now 👍 I'd be interested in figuring that out at some point if this function comes up again.

2021-08-10 13:57 UTC, chrisjpurdy commented on src/app/services/validation.ts
> +        (SITE_SUBJECT !== SITE.CS || (userPreferences.BETA_FEATURE?.BOOLEAN_NOTATION === null || validateBooleanNotation(userPreferences.BOOLEAN_NOTATION)));
![image](https://user-images.githubusercontent.com/33040507/128880016-51f78a17-0156-4eae-b741-128173c42eab.png)

2021-08-10 13:59 UTC, chrisjpurdy commented on src/app/services/validation.ts
> +        (SITE_SUBJECT !== SITE.CS || (userPreferences.BETA_FEATURE?.BOOLEAN_NOTATION === null || validateBooleanNotation(userPreferences.BOOLEAN_NOTATION)));
Added in the upcoming commit - just wondering whether a choice of Boolean logic notation should even be a required account setting, since it is quite specific?

2021-08-11 13:41 UTC, mlt47 commented on src/app/services/validation.ts
> +        (SITE_SUBJECT !== SITE.CS || (userPreferences.BETA_FEATURE?.BOOLEAN_NOTATION === null || validateBooleanNotation(userPreferences.BOOLEAN_NOTATION)));
That looks neat. But yes, after thinking about the GCSE student case in particular (where the boolean logic notation option is not actually relevant to them) you might be right and we should not "require" the setting of that option. It can be there on the account page if they want to change it but they should not be forced to consider it. It is worth confirming this with Allen of the RPF team.
If we are not making it required, I would suggest also having a DB migration script which gives existing users the notation that they are used to seeing depending on their exam board (be careful as there is both an exam board field in the users table and as a user_preference, I think we use the users one - we'll remove and replace both for a new field with my changes soon which will clear things up a little). This will make sure that the site doesn't change behaviour suddenly for them without them triggering that change.

Ah well, good to have refactored out the component anyway!

2021-08-17 08:19 UTC, mlt47 reviewed
I've made a few further comments after reviewing Ben's similar PR more thoroughly

2021-08-17 14:26 UTC, chrisjpurdy commented on src/app/components/elements/inputs/BooleanNotationInput.tsx
> +            <option value={undefined}></option>
I've removed the `undefined` option in the latest commits - the 'default' is an option that sets both flags in `booleanNotation` to `false`

2021-08-17 14:27 UTC, chrisjpurdy commented on src/app/components/elements/inputs/BooleanNotationInput.tsx
> +                Object.keys(BOOLEAN_NOTATION).reduce((val: string | undefined, key) => booleanNotation[key as keyof BooleanNotation] === true ? key : val, undefined)
I've removed that `=== true` (my bad) and have changed the default value to a new `BOOLEAN_NOTATION.NONE`, which doesn't have a corresponding flag in the `BooleanNotation` type but corresponds to both flags set to `false`

2021-08-17 14:27 UTC, chrisjpurdy commented on src/app/components/elements/LaTeX.tsx
> +                    }
Sorted!

2021-08-17 14:29 UTC, chrisjpurdy commented on src/app/components/elements/inputs/BooleanNotationInput.tsx
> +            <option value={undefined}></option>
`<option value={BOOLEAN_NOTATION.NONE}>No preference</option>` - line 39 in `BooleanNotationInput.tsx`

2021-08-19 15:56 UTC, mlt47 approved these changes
Merged into `september` and altered slightly. Will now close this PR to try and avoid confusion.

2021-08-19 15:56 UTC, mlt47 commented
Merged into `september` will get merged into `master` in time

2021-08-19 15:56 UTC, closed without merging