CS Question finder MVP
isaacphysics/isaac-react-app pull request #461
Opened 2021-10-22 13:47 UTC by chrisjpurdy

Allows filtering by topic, exam board, stage, and difficulty. It looks similar to the teacher gameboard builder, but without the option to search by question name. 
A small back-end change was also needed to allow the gameboards to be generated intuitively considering the user only has the option to select topics ([see this PR](https://github.com/isaacphysics/isaac-api/pull/392)).

The reveal button on the question finder has changed colour a tiny bit (on physics) so that it has the correct-ish colour on both sites. (it might need brightening so that it stands out more perhaps)

2021-11-02 16:23 UTC, mlt47 requested changes
This is good and also includes the concepts options by reusing an existing endpoint which is nice. If we find it is slow we can always optimise later.

There are a few suggested changes. I am also going to have a play with the CS filter layout in case there is another configuration which looks nicer/reads better.

2021-11-02 16:23 UTC, mlt47 commented on src/app/components/pages/Gameboard.tsx
> +const GameboardItemComponent = ({gameboard, question, showBreadcrumbs}: {gameboard: GameboardDTO, question: GameboardItem, showBreadcrumbs?: boolean}) => {
Is there a reason why we don't show breadcrumbs all the time (if they're present)? As there is no GameboardItemComponent or GameboardViewer with showBreadcrumbs explicitly set to false with the logic on line 85 I think this might already be true?

2021-11-03 12:04 UTC, chrisjpurdy commented on src/app/components/pages/GameboardFilter.tsx
> +        {SITE_SUBJECT === SITE.PHY && <RS.Col lg={8}>
I thought I'd removed all of these! Oops

2021-11-04 15:37 UTC, mlt47 commented on src/app/components/pages/GameboardFilter.tsx
> +        .map(concept => ({label: "<!LOADING!>", value: concept}));
You can use QUESTION_FINDER_CONCEPT_LABEL_PLACEHOLDER

2021-11-04 15:43 UTC, mlt47 commented on src/app/services/constants.ts
> +export const QUESTION_FINDER_CONCEPT_LABEL_PLACEHOLDER = "<!LOADING!>";
I personally slightly prefer "Loading..." but don't feel super strongly about it.

2021-11-11 09:45 UTC, mlt47 approved these changes

2021-12-14 11:22 UTC, mlt47 requested changes

2021-12-14 11:22 UTC, mlt47 commented on src/app/services/miscUtils.ts
> +    return cs;
I was initially uneasy about this because of needing to remember the order of positional arguments, however, WebStorm at least tells you the argument names at wherever the method is called. That doesn't happen yet in GitHub which is a little annoying.
The other thing to consider is if/when we add a new subject. For that we can make the new argument's type `, art: NonNullable<A>` to make sure we update all the old calls to this siteSpecific function.
We already have a thing called siteSpecific which is a map of constants which are immediately evaluated to either be the Physics or CS version. We will have to alias or namespace imports if we use both in the same file which is a little annoying and it might get confusing in discussion although ultimately does the same thing. Is there perhaps a suitable alternative name? Maybe the other one becomes siteSpecificComponents or something?
Despite all this, (in WebStorm) it does look neater than short circuited &&s all over the place.
I propose we carry on with this for a little to see how it feels in practice as it is easy enough to revert the decision later.

2021-12-14 11:22 UTC, mlt47 commented on src/app/components/pages/GameboardFilter.tsx
> +                    </RS.Col>
Did you mention to Physics that this was being re-enabled? It can be a separate card now but I think they would be interested

2021-12-14 11:22 UTC, mlt47 commented on src/app/components/pages/GameboardFilter.tsx
> +                        Edit question filters ✎
Might this icon also be useful (and if anything more appropriate) for the title editing button?
I would also suggest at least trying to see how that title editing button looks outlined or in a less impactful colour with less padding between it and the title so that it is more clear that they are related.

2021-12-14 12:00 UTC, chrisjpurdy commented on src/app/services/miscUtils.ts
> +    return cs;
I was also unsure about whether to consider new subjects or not, but I felt like it would be such a rare occurrence and be so simple to find and replace usages that fully generifying it would be overkill. Hopefully it is easier to use than the &&s!

2021-12-14 12:01 UTC, chrisjpurdy commented on src/app/components/pages/GameboardFilter.tsx
> +                    </RS.Col>
I didn't, but I thought that I made sure this was only on CS

2021-12-14 12:05 UTC, chrisjpurdy commented on src/app/components/pages/GameboardFilter.tsx
> +                        Edit question filters ✎
Good idea - I'll give each a go and see what works best. I feel like it is fairly clear they are related just based on the button text - the reason there is a bit of padding is because I had to pick classes for responsiveness, but I'll give this a go again to see if there's a better solution.

2021-12-22 15:19 UTC, mlt47 approved these changes

2021-12-22 15:19 UTC, merged