Cloze drag and drop questions
isaacphysics/isaac-react-app pull request #465
Opened 2021-11-09 15:41 UTC by chrisjpurdy

I think these are finally ready to merge.

This builds on @mlt47's demo with the following addtions:
 - Clear button on inline drop-zones (only if zone contains an item)
 - Disallow dragging out of inline drop-zones (because of the horrible bug\*)
 - A boolean attribute `withReplacement` on the question DTO, specifying whether items given can be used only once, or duplicated an unbounded amount of times
 - Support for inline drop-zones inside MathJax-rendered KaTeX. This was mostly just removing the `display: block;` CSS attribute, because it caused drop-zones that overflow `div.katex` to be cut-off. Un-setting this attribute is only done if the question is an `isaacClozeQuestion`

\* `react-beautiful-dnd` doesn't support lists with a limited number of items. While we can try to force an inline drop-zone to stay at a certain height with CSS, for some reason it expands its height when having an item dragged out of it (if I knew why this happens, it could be fixed probably, but I've got no clue at all)

2021-11-11 10:42 UTC, mlt47 commented on src/IsaacApiTypes.tsx
> +}
This now extends IsaacItemQuestionDTO

2021-11-12 11:54 UTC, mlt47 requested changes
This works nicely. I like the cancel workaround - it looks neat.
It would be nice to find a way of avoiding using the library component's ID for changes if it is an undocumented part of the library, but is not a critical piece of functionality so if there is no workaround it is fine, but maybe specify that the querySelector could return `null`. Other suggestions are small.

2021-11-12 11:54 UTC, mlt47 commented on src/app/components/content/IsaacClozeQuestion.tsx
> +                    />
Because the drop zones are larger than the line height, they overlap if line-wrapping leads to a drop zone appearing underneath another.

2021-11-15 15:07 UTC, chrisjpurdy commented on src/app/components/content/IsaacClozeQuestion.tsx
> +            const inlineDrop = document.querySelector(`[data-rbd-droppable-id="${dropid}"]`) as HTMLElement;
I've changed the selector to `div[id="${dropid}"] > div > div`, which selects the same element, but instead using an `id` attribute (that we specify) of a parent `div`.

2021-11-15 16:14 UTC, chrisjpurdy commented on src/app/components/content/IsaacClozeQuestion.tsx
> +                    inlineDrop.className = inlineDrop.className.replace("border border-dark", "") + " border border-dark";
I've fixed this (and made the above fix obsolete) by maintaining a `borderMap` state, which is a map from drop zone id to `boolean`, and passing each respective boolean value (signifying whether to show the border or not) into each of the `InlineDropRegion` components.

2021-11-15 16:26 UTC, chrisjpurdy commented on src/IsaacApiTypes.tsx
> +}
Done!

2021-11-15 16:42 UTC, chrisjpurdy commented on src/app/components/content/IsaacClozeQuestion.tsx
> +                    />
Fixed by adding a `2px` margin to inline drop-zones outer-most `div`

2021-11-15 21:40 UTC, mlt47 approved these changes
Great

2021-11-16 09:13 UTC, merged