Names fasttrack questions with the new suggested scheme
isaacphysics/isaac-react-app pull request #468
Opened 2021-11-11 16:45 UTC by chrisjpurdy

Also makes sure that gameboard representation of fasttrack question titles is the same as their title on a question page (i.e. has the i for upper or ii for lower)

See [this card](https://trello.com/c/2sahDjkq/2130-change-to-automatic-naming-of-fast-track-maths-questions) for details.

2021-11-19 18:07 UTC, mlt47 requested changes
Small refactoring suggestion.
Moving that pure utility function out into a service will also hopefully reduce the chance of us inadvertently crating a cyclic dependency in the imports!

We also display the title in other places such as search results, and navigation links as you move between questions in a gameboard so worth having a little search for those.

2021-11-23 11:41 UTC, chrisjpurdy commented on src/app/components/pages/Gameboard.tsx
> +    }
Done!

2021-11-23 11:42 UTC, chrisjpurdy commented on src/app/components/pages/Question.tsx
>  }
Done this as well - I've tried to make sure that question titles are consistent everywhere, but in navigation links there isn't enough information about the content being linked to yet to call `generateQuestionTitle` (missing `type` and `tags`)

2021-11-26 10:42 UTC, mlt47 approved these changes
Great

2021-11-26 10:42 UTC, merged