Combined Markbook
isaacphysics/isaac-react-app pull request #471
Opened 2021-11-19 12:20 UTC by Morpheu5

This adds a per-group summary view of quiz progress to the old Assignment Progress / My Markbook page.

There is now a significant amount of shared code between `AssignmentProgress.tsx` and `QuizTeacherFeedback.tsx` so I made a new `QuizProgressCommon.tsx` file for better reusability.

2021-11-30 17:41 UTC, mlt47 requested changes
Small suggestions but works well

2021-11-30 17:41 UTC, mlt47 commented on src/app/components/pages/AssignmentProgress.tsx
>  import {selectors} from "../../state/selectors";
The nav bar and and page title will need updating (for Physics, at least)

2021-11-30 17:41 UTC, mlt47 commented on src/app/components/pages/AssignmentProgress.tsx
> +    }, [quizAssignments])
As userFeedback is a "derived" field, it doesn't need a useState(). You can do something like the following and it will always be correct because the changing of the quizAssignments redux state will trigger the re-render, i.e. re-execution of this function. 
```
let userFeedback: QuizUserFeedbackDTO[] = [];
if (resourceFound(quizAssignments)) {
    userFeedback = quizAssignments.find(qa => qa.id === quizAssignmentId)?.userFeedback);
}
    
```

2021-11-30 17:41 UTC, mlt47 commented on src/app/components/pages/AssignmentProgress.tsx
> +    const [activeTab, setActiveTab] = useState(MARKBOOK_TYPE_TAB.assignments);
Physics want test to be active first, possibly conditional on whether or not there are any tests, but it is worth clarifying that with them.

2021-12-01 11:48 UTC, Morpheu5 commented on src/app/components/pages/AssignmentProgress.tsx
>  } from "../../../IsaacAppTypes";
Yes, the jury's out on the new name, I guess…

2021-12-01 11:54 UTC, Morpheu5 commented on src/app/components/pages/AssignmentProgress.tsx
> +                }
I agree, I don't like the `-1` either. Having an `as number` would force the cast and I don't think TS likes that. I guess I could add a `defined`ness guard on the `qa.groupId` bit and skip over if that is not defined as in practice we are unlikely to ever use whatever gets added to the `-1` key. OTOH, we lose that information, although it's not like we do much with it.

2021-12-01 12:00 UTC, Morpheu5 commented on src/app/components/pages/AssignmentProgress.tsx
> +type AppGroupWithAssignments = AppGroup & {assignments: EnhancedAssignment[], quizAssignments: any};
Huh, well spotted!

2021-12-01 12:01 UTC, Morpheu5 commented on src/app/state/actions/quizzes.tsx
> +};
Moved it.

2021-12-01 12:40 UTC, Morpheu5 commented on src/app/components/pages/AssignmentProgress.tsx
>      useEffect(() => {
There's a cascade of types and subtypes that makes the whole thing very painful to pick apart. I tried for a whole minute and ran away screaming. Some of the types have also drifted apart, with the likes of the `EnhancedAssignment` to include progress which the `QuizAssignmentDTO` does not need because it already includes it, so maybe a full review/rationalization of the types on this page is in order.

2021-12-01 12:41 UTC, Morpheu5 commented on src/app/components/pages/AssignmentProgress.tsx
>  import {selectors} from "../../state/selectors";
Physics currently calls it "Assignment Progress", CS calls it "My markbook". It's an easy change, just needs a decision.

2021-12-01 12:44 UTC, Morpheu5 commented on src/app/components/pages/AssignmentProgress.tsx
> +    }, [quizAssignments])
Good point. I guess I have been resorting to using state by default out of trying to avoid potential issues when not using it.

2021-12-01 12:45 UTC, Morpheu5 commented on src/app/components/pages/AssignmentProgress.tsx
> +    const [activeTab, setActiveTab] = useState(MARKBOOK_TYPE_TAB.assignments);
I've asked Matthew to clarify with both content teams.

2021-12-01 14:00 UTC, Morpheu5 commented on src/app/components/pages/AssignmentProgress.tsx
> +    if (isDefined(group.quizAssignments) && Array.isArray(group.quizAssignments) && group.quizAssignments.length > 0) {
Huh, I remember now: this was a [useless](https://lgtm.com/projects/g/isaacphysics/isaac-react-app/rev/pr-260ac0b644b577b16ce04cdf9fc6a2f2757bed9d) alert from LGTM.

2021-12-14 11:52 UTC, mlt47 commented on src/app/components/pages/AssignmentProgress.tsx
> +            `Tests (${groupTests.length || 0})`: groupTests
I think this commit is broken because JS object keys only get evaluated if they are in `[`...`]`

2021-12-16 10:00 UTC, mlt47 commented on src/app/components/pages/AssignmentProgress.tsx
>  import {selectors} from "../../state/selectors";
Physics have decided to continue with the existing names for now.

2021-12-16 10:00 UTC, mlt47 approved these changes

2021-12-16 10:02 UTC, merged