Update dependencies
isaacphysics/isaac-react-app pull request #473
Opened 2021-11-23 10:52 UTC by Morpheu5

# Summary

Dependabot has been screaming loudly for a while so this PR updates the following dependencies, directly or indirectly, which were reported as either **critical** or **high** severity.

- immer
- ssri
- trim-newlines
- tar
- ansi-html
- is-svg
- glob-parent
- axios

# Changes

This PR also upgrades `package-lock.json` to version 2, and this requires npm >= 7. It may or may not also require Node >= v14 due to some compilation issues in some dependencies. It should be a good idea to upgrade anyway. The current Node LTS is v16 while v14 was the previous.

**`node-sass` vs `sass` and the Bootstrap 4 controversy:** `node-sass` is native, not JS, and needs to be compiled natively for the architecture of the each machine. It was not compiling on my `arm64` Mac, and the suggested solution was to move to `sass` which is JS-based. This brought in a newer version of SCSS (the language) which deprecates the use of `/` as numeric division, replaced by `math.div(a, b)`. Bootstrap 4 is full of these, so I tried migrating to Bootstrap 5, but that made everything worse as version 5 deprecates a whole load of mixins and functions that we use all over the place. So, for the moment we are stuck with Bootstrap 4 and we'll have to live with deprecation warnings all over the place. Sorry.

**webpack 5:** to upgrade one of the dependencies (`glob-parent` IIRC) I had to upgrade webpack from 4 (or 3?) to 5. This was *mostly* painless but we should be aware that the build system is now one or more major version(s) ahead. I can't see how this could be a problem, but hey.

# Actions and testing

It seems that we are all using at least version 7 of npm, which is a good thing. We may also want to upgrade Node to v14 or above. I would like everyone on the team to check out this branch and try the following:

- `npm ci` first just to make sure everything works as expected
- `npm i` to make sure your npm doesn't overwrite the whole `package-lock.json` file for no reason (yes, it did happen in the past, it was not fun, ask James)
- `npm run start-(phy|cs)` and check that your dev environment still works
- `npm run build-(phy|cs)` and check that you can build a production bundle
   - technically, this is not necessary, but it will just give me a little more confidence that nothing is going to break in a major way further down the line

2022-01-27 09:29 UTC, mlt47 commented
@Morpheu5, I've had a bit of a google and it looks like the source of the current problem is that we're using `history` v5 with `react-router` v5 where as we should be using `history` v4 for `react-router` v4 or v5. https://stackoverflow.com/questions/62591351/how-to-push-to-history-in-react-router-v5

It also looks we can safely uninstall react-router as we install and import `react-router-dom` which itself re-exports all of `react-router`'s exports. That would be a useful additional commit, with a few changes to import statements.
https://github.com/remix-run/react-router/issues/4648#issuecomment-284479720

2022-03-18 11:58 UTC, mlt47 requested changes
A lot of work here, it'll be great to get it in and off the long-lived branch. I've made some comments and suggestions to review before that.

2022-03-18 11:58 UTC, mlt47 commented on src/app/services/select.ts
>  }
This is quite fun but I wonder if having two functions selectOnChange and selectOnChangeAndUnwrap would be more readable, even if one used the other to avoid duplication?

2022-03-18 11:58 UTC, mlt47 commented on src/app/components/elements/Accordion.tsx
> +    location: History.Location;
location should be defined in RouteComponentProps

2022-03-18 11:58 UTC, mlt47 commented on src/app/components/pages/AssignmentProgress.tsx
> +    function openAssignmentDownloadLink(event: React.MouseEvent<HTMLButtonElement & HTMLAnchorElement>) {
Is `|` more correct than `&` here?

2022-03-18 13:14 UTC, Morpheu5 commented on config/jest/jest.config.common.js
> +        // "enzyme"
Having either of those or none at all doesn't seem to make any difference at the moment, but I didn't want to commit to removing it entirely in case it becomes a problem in the future and this could provide a hint…

2022-03-18 13:19 UTC, Morpheu5 commented on config/webpack.config.common.js
> +                            test: /\.(png|gif|svg)$/,
Huh, that's a good question. I put them back, but I didn't notice them missing from the site so… I'm confused. PNGs certainly were a problem with SCSS…

2022-03-18 13:24 UTC, Morpheu5 commented on config/webpack.config.common.js
> +                                isProd ? { loader: MiniCssExtractPlugin.loader, options: { esModule: false } } : null,
I think this was an issue with how TS imports the SCSS files, if I turn it to true I get a bunch of warnings like the following:

```
WARNING in ./src/scss/phy/isaac.scss 22:17-24
export 'default' (imported as 'content') was not found in '!!../../../node_modules/mini-css-extract-plugin/dist/loader.js??ruleSet[1].rules[0].oneOf[3].use[1]!../../../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].oneOf[3].use[2]!../../../node_modules/sass-loader/dist/cjs.js!./isaac.scss' (module has no exports)
 @ ./src/index-phy.tsx 3:0-31
 ```

2022-03-18 13:25 UTC, Morpheu5 commented on package.json
> +    "@react-google-maps/api": "^2.7.0",
Yeah, well spotted.

2022-03-18 13:26 UTC, Morpheu5 commented on package.json
> +    "file-loader": "^6.2.0",
Indeed.

2022-03-18 13:28 UTC, Morpheu5 commented on package.json
> +    "redux-mock-store": "^1.5.4",
I suspect only `redux-mock-store` needs to be a devDep, the others have runtime parts that need to go in, right?

2022-03-18 13:32 UTC, Morpheu5 commented on package.json
> +    "npm-force-resolutions": "^0.0.10",
Yes.

2022-03-18 13:35 UTC, Morpheu5 commented on package.json
> +    "ajv": "^8.9.0",
Probably a leftover from when I was trying to cling on to `npm`.

2022-03-18 13:40 UTC, Morpheu5 commented on src/app/components/content/IsaacContent.tsx
> +    match: match & { path: string },
Do you mean something like getting rid of `match` and replacing the extended type with `RouteComponentProps<{ path:string }>`?

2022-03-18 13:41 UTC, Morpheu5 commented on package.json
> +    "url-loader": "^4.1.1"
`url-loader`? Are you sure?

2022-03-18 13:53 UTC, Morpheu5 commented on src/app/components/elements/LaTeX.tsx
> +// @ts-ignore
There are but they seem broken. The recommended way to access `utils` is to import `{ Remarkable }` and then go `Remarkable.utils`, but this is not defined so the app crashes. Conversely, the type says that `utils` isn't exported by `"remarkable"`, but if I just import it straight out of the package as `import { utils } from "remarkable"` and ts-ignore it, and just plain use it as, for example, `utils.escapeHtml(markup)` then everything runs again.

2022-03-18 13:57 UTC, Morpheu5 commented on src/app/components/elements/inputs/DateInput.tsx
> +                // @ts-ignore <- I am NOT sure this is a good idea...
We are forcing an assignment between two types that are effectively compatible, one from a ChangeEvent and one from a MouseEvent, but not the same as far as TS goes, and I couldn't figure out better typing.

2022-03-18 14:15 UTC, Morpheu5 commented on src/app/components/pages/AllTopics.tsx
> +                <Link // REVIEW This may be not the intended behaviour, but that LinkTag thing above is horrendous in terms of types.
It actually seems fine like this, I don't understand why it was using `LinkTag` in that form in the first place…

2022-03-18 14:19 UTC, Morpheu5 commented on src/app/components/pages/Events.tsx
> +export const Events = withRouter<RouteComponentProps, any>(({history, location}: {history: History; location: Location}) => {
If I get rid of that, they become implicitly `any`, so I'm tempted to leave them, for as ugly as they look…

2022-03-18 14:25 UTC, Morpheu5 commented on src/app/components/pages/SingleAssignmentProgress.tsx
> +    function openAssignmentDownloadLink(event: React.MouseEvent<HTMLAnchorElement & HTMLButtonElement>) {
Ehm… no… I wish… Unfortunately it has to be both, otherwise set algebra steps in and this is the result:

```
TS2339: Property 'href' does not exist on type 'EventTarget & (HTMLAnchorElement | HTMLButtonElement)'.
  Property 'href' does not exist on type 'EventTarget & HTMLButtonElement'.
```

2022-03-18 14:31 UTC, Morpheu5 commented on src/app/services/scrollManager.ts
>  });
I would assume so but I can't make heads or tails of the type, and leaving it to be inferred seems to result in the wrong one. I followed the types as far as I could and I found somewhere that the type of the parameter of `history.listen()` has `location` and `action` but I can't see how to extract them.

2022-03-18 14:36 UTC, Morpheu5 commented on config/jest/tsTransform.js
> +            "@babel/preset-typescript"
Ah, turns out these may not be necessary anymore now that we use `ts-jest` instead of babel.

2022-03-18 14:37 UTC, Morpheu5 commented on src/app/components/elements/modals/QuizSettingModal.tsx
> -                value={selectedGroups}
@chrisjpurdy was this you?

2022-03-18 14:39 UTC, Morpheu5 commented on src/app/components/elements/modals/QuestionSearchModal.tsx
> +                    onChange={(s: MultiValue<Item<ExamBoard>>) => selectOnChange(setSearchExamBoards, true)(s)}
This was definitely @chrisjpurdy

2022-03-18 14:39 UTC, Morpheu5 commented on src/app/services/select.ts
>  }
@chrisjpurdy again, I gave up trying to understand this a long time ago…

2022-03-18 14:40 UTC, Morpheu5 commented on src/app/components/pages/AssignmentProgress.tsx
> +    function openAssignmentDownloadLink(event: React.MouseEvent<HTMLButtonElement & HTMLAnchorElement>) {
Same as [this](https://github.com/isaacphysics/isaac-react-app/pull/473#discussion_r830051051).

2022-03-18 14:42 UTC, Morpheu5 commented on package.json
> +    "querystring-es3": "^0.2.1",
I'm not sure about any of these, they seem to be used in various different ways throughout the app and build config.

2022-03-25 13:32 UTC, chrisjpurdy commented on src/app/components/elements/modals/QuestionSearchModal.tsx
> +                    onChange={(s: MultiValue<Item<ExamBoard>>) => selectOnChange(setSearchExamBoards, true)(s)}
Typescript doesn't infer the type of `s` for me - when I remove it, it thinks the second parameter (`true`) should be of type `void` and falls over.

2022-03-25 14:27 UTC, chrisjpurdy commented on src/app/components/elements/modals/QuizSettingModal.tsx
> -                value={selectedGroups}
I think it was - I've tested it locally now and it doesn't seem to make any difference at all.

2022-03-25 14:41 UTC, chrisjpurdy commented on src/app/services/select.ts
>  }
Yeah I kind of agree @mlt47, but by doing it like this the type of `unwrapValue` is inferred and you're forced by Typescript to use the correct one based on the given "set state" function. 
This couldn't be done if there were two functions, and the type error created by using the wrong one might be incoherent and might not necessarily lead someone to try the other one unless they've read the docs. 
Admittedly, if you're using a state type that isn't compatible with this (not `T` or `Item<T>`), then the error message `x is not of type void` isn't exactly helpful either.
I'm not sure what the lesser evil is honestly.

2022-04-01 17:14 UTC, mlt47 requested changes
We should check about the All Topics page change with the CS content team but otherwise I think it's done 👍

2022-04-01 17:14 UTC, mlt47 commented on src/app/services/select.ts
>  }
OK let's stick with this for now.

2022-04-01 17:14 UTC, mlt47 commented on src/app/components/pages/SingleAssignmentProgress.tsx
> +    function openAssignmentDownloadLink(event: React.MouseEvent<HTMLAnchorElement & HTMLButtonElement>) {
OK not enough of a problem to hold this back

2022-04-04 10:48 UTC, chrisjpurdy approved these changes
Tested a lot of features that were touched on in these changes locally and nothing seems to have broken. A lot of the changes are to do with types and don't affect the runtime behaviour anyway. Just had a couple of comments but shouldn't hold back on merging - LGTM! 🍾

2022-04-04 10:48 UTC, chrisjpurdy commented on src/app/components/pages/NotFound.tsx
> +                        {(state && (state as any).overridePathname) || pathname}
@Morpheu5 @mlt47 I've got a way of writing this component (and `Unauthorised`) with the `useLocation` hook that avoids HOCs and casting to `any` - happy if I commit these?

2022-04-04 11:21 UTC, chrisjpurdy commented on src/app/components/pages/NotFound.tsx
> +                        {(state && (state as any).overridePathname) || pathname}
Committed this after daily meet on 04/04

2022-04-05 10:25 UTC, Morpheu5 commented on src/app/components/pages/AllTopics.tsx
> +                <Link
The workaround is ugly but should at least restore the functionality as it was intended to be.

2022-04-05 10:31 UTC, Morpheu5 commented on src/app/components/elements/Accordion.tsx
> +                        <span className="accordion-part p-3 text-secondary">Part {ALPHABET[(index as number) % ALPHABET.length]}  {" "}</span>
I don't actually know why, but it does wreak havoc everywhere we use `Accordion` without an `index` property – which we do a fair amount of times and I'm not sure what it was meant to mean.

2022-04-05 10:35 UTC, Morpheu5 commented on src/app/components/elements/Accordion.tsx
> +                        <span className="accordion-part p-3 text-secondary">Part {ALPHABET[(index as number) % ALPHABET.length]}  {" "}</span>
Indeed, the way we use it here looks suspicious. Worst case scenario, though, we generate the string "Part NaN", here, so it's probably not that catastrophic, but definitely worth having a second look.

2022-04-11 08:19 UTC, Morpheu5 commented on src/app/components/pages/AllTopics.tsx
> +                <Link // REVIEW This may be not the intended behaviour, but that LinkTag thing above is horrendous in terms of types.
Well anyway, I replaced this with a kind of a somewhat ugly-ish workaround that restores the `span` when necessary.

2022-04-11 09:03 UTC, mlt47 commented on src/app/components/pages/Question.tsx
>  }
I seem to remeberm passing the expected match value to the RouteComponentProps works and is preferable:
```
interface QuestionPageProps extends RouteComponentProps<{questionId: string}> {
    questionIdOverride?: string;
}
```

2022-04-11 09:49 UTC, merged