Adds stage and difficulty progress donut to Phy
isaacphysics/isaac-react-app pull request #483
Opened 2021-12-13 11:14 UTC by bh412

Relies on corresponding backend PR to add the necessary information to the /progress object

2022-02-01 15:53 UTC, mlt47 reviewed
A few small comments re. the code. Haven't tested how it looks but the commit messages sound like the colours were approved by the Physics content team.

2022-02-01 15:53 UTC, mlt47 commented on src/app/components/elements/views/QuestionProgressCharts.tsx
> +    const [stageChoice, setStageChoice] = useState<{value: STAGE; label: string}>({value: STAGE.A_LEVEL, label: "A Level"});
Quite sure we have a STAGE_OPTIONS constant somewhere which could be used rather than redefining the label here.

2022-02-01 15:53 UTC, mlt47 commented on src/app/components/elements/views/QuestionProgressCharts.tsx
> +            return Object.keys(difficultyLabelMap).indexOf(a) - Object.keys(difficultyLabelMap).indexOf(b);
comparatorFromOrderedValues(stagesOrdered) might be neater here

2022-02-01 16:19 UTC, chrisjpurdy requested changes
I think a few small tweaks are needed for code maintainability but the change is generally good!
Playing around with the donuts to test them made me feel that, if you have selected a topic or stage for which you have no data, the donut should be removed and show "No data". I don't know if this is intended or not, but it didn't make sense to me to select Waves in the topic dropdown and still be shown my progress on Mechanics questions (because I had no data on Waves questions). In any case, that particular change/fix should probably be a separate card.

2022-02-01 16:19 UTC, chrisjpurdy commented on src/app/components/elements/views/QuestionProgressCharts.tsx
> +        if (SITE_SUBJECT === SITE.PHY && !isAllZero(difficultyColumns || [])) {
Doesn't matter really but `difficultyColumns` will always be an array given how it's defined, so the `|| []` check isn't needed.

2022-02-01 16:19 UTC, chrisjpurdy commented on src/app/components/elements/views/QuestionProgressCharts.tsx
> +        {SITE_SUBJECT === SITE.PHY && <RS.Col xl={12/noCharts} md={4} className="mt-4 d-flex flex-column">
It looks like `md` is defined as `12/noCharts` as well?

2022-02-01 16:19 UTC, chrisjpurdy commented on src/app/services/constants.ts
> +        "Practice\u00A0(P1)": "#509e2e",
I think the above line should be: 
`[difficultyLabelMap.practice_1]: "#509e2e",`
and similarly for each of the colours for the other difficulty labels.
This saves changing labels in more places than necessary in the future, because any changes to `difficultyLabelMap` should affect how they are displayed on these donuts.

2022-02-01 17:13 UTC, bh412 commented
@chrisjpurdy On the 'disappear if nothing for selected' bit, I think I'm inclined to agree, although if doing that we should do the same for the questions by subject donut too!

2022-02-02 09:15 UTC, bh412 commented on src/app/components/elements/views/QuestionProgressCharts.tsx
>      const levelColumns = [...Array(7)].map((_, i) => [`Level ${i}`, questionsByLevel[i as Levels] || 0]);
That's true! I can include that cleanup in this PR too

2022-02-07 15:19 UTC, bh412 commented on src/app/components/elements/views/QuestionProgressCharts.tsx
> +            return Object.keys(difficultyLabelMap).indexOf(a) - Object.keys(difficultyLabelMap).indexOf(b);
I can't get this to work properly without some `@ts-ignore`s - it really doesn't like being convinced that the type of `questionsByStageAndDifficulty[stageChoice.value]` is anything other than number, despite it being Difficulty

2022-02-08 09:08 UTC, bh412 commented on src/app/components/elements/views/QuestionProgressCharts.tsx
> +    const [stageChoice, setStageChoice] = useState<{value: STAGE; label: string}>({value: STAGE.A_LEVEL, label: "A Level"});
Phy asked for A-Level but maybe I could alter it

2022-02-08 11:08 UTC, merged