Adds new alevel, gcse and all colours to cs topic and concept pages
isaacphysics/isaac-react-app pull request #501
Opened 2022-02-09 10:39 UTC by bh412

I believe topics aren't used on Physics, otherwise I'll add a site check there too

2022-02-24 15:09 UTC, mlt47 requested changes

2022-03-08 11:39 UTC, bh412 commented on src/app/components/elements/Accordion.tsx
> +                {isConceptPage && audienceString && <span className={"accordion-label" + (SITE_SUBJECT === SITE.CS && audienceStyle(audienceString)) + " badge-secondary d-flex align-items-center just
I've pushed a change which neatens this a bit - I'm not certain that using classNames would help so much, with it needing a check on whether it is alevel / gcse / all and then displaying the relevant class?

2022-03-10 09:50 UTC, bh412 commented on src/app/components/elements/Accordion.tsx
> +                {isConceptPage && audienceString && <span className={"accordion-label" + (SITE_SUBJECT === SITE.CS && audienceStyle(audienceString)) + " badge-secondary d-flex align-items-center just
Implemented now, thanks for explaining!

2022-03-14 11:47 UTC, mlt47 approved these changes
Great, I think that's neater even if there is a bit more thinking to do to figure out exactly what is happening. 

You could probably also get rid of one of the scss files and maybe rename the other to be more general and then it can be applied to both instances depending on just the `stage-label-...` class. Removing the duplication will reduce the chance of a bug being accidentally introduced if we were to ever update one but forget to update the other.

Otherwise fine and happy for you to merge.

2022-03-14 14:02 UTC, merged