Isaac code editor iframe wrapper component
isaacphysics/isaac-react-app pull request #517
Opened 2022-03-04 16:06 UTC by chrisjpurdy

This adds the element that opens an `iframe` to [editor.isaaccode.org](editor.isaaccode.org), passing it data specified in content.

Adding this will mean that the code editor can be used from the live site (the editor changes haven't been merged yet, so the only way to make this content block type is by running the editor locally on the `feature/interactive-code-blocks` branch)

2022-03-16 11:14 UTC, Morpheu5 requested changes
Looks OK other maybe than the two comments.

2022-03-25 11:14 UTC, chrisjpurdy commented on src/app/services/questions.ts
> +        for (const symbol of saneState.symbols) {
This was automatically done by WebStorm, and didn't disagree with it either so left them in 😅

2022-03-25 11:14 UTC, chrisjpurdy commented on src/app/components/content/IsaacInteractiveCodeSnippet.tsx
> +    return <iframe title={"Code Sandbox"} src={"http://localhost:3000/#" + uid.current} ref={iframeRef} onLoad={sendQuestion} className={"isaac-code-iframe w-100 mb-1"} style={
Definitely not! I'll fix that

2022-03-25 13:42 UTC, Morpheu5 approved these changes

2022-03-25 13:42 UTC, Morpheu5 commented on src/app/services/questions.ts
> +        for (const symbol of saneState.symbols) {
Oh, alright then 😄

2022-03-25 13:49 UTC, merged