Show a single accordion section even if it's irrelevant to the user
isaacphysics/isaac-react-app pull request #524
Opened 2022-03-11 11:59 UTC by Morpheu5

To do:

- [ ] Check that it doesn't mess with any regular content
- [ ] Check the alert message with the content team
- [ ] Make sure that it actually does what I think it does

2022-03-18 14:48 UTC, mlt47 requested changes

2022-03-18 14:48 UTC, mlt47 commented on src/app/components/content/IsaacAccordion.tsx
> +    const hashAnchor = location.hash.includes('#') ? location.hash.slice(1) : 'undefined-string-will-never-match';
Probably worth using the `const {hash} = useLocation();` so that it updates on following soft links (although it is less important for this particular feature, a future feature would assume it would update).

2022-03-18 14:48 UTC, mlt47 commented on src/app/components/content/IsaacAccordion.tsx
> +    const hashAnchor = location.hash.includes('#') ? location.hash.slice(1) : 'undefined-string-will-never-match';
Isn't `null` better than 'undefined-string-will-never-match' here? You later check if hashAnchor is equal to the value, if there is an accidental typo in either it will never reach that case and the compiler won't complain because the standard type is string.

2022-03-18 14:48 UTC, mlt47 commented on src/app/components/content/IsaacAccordion.tsx
> +                if ((section.id || "").includes(hashAnchor)) {
Using `includes` here rather than equality would do the incorrect thing if there were accordion sections `hash`, `hash-map`, `hash-set`, `rehash` and the user followed the link for `#hash`.

2022-03-18 15:27 UTC, Morpheu5 commented on src/app/components/content/IsaacAccordion.tsx
> +    const hashAnchor = location.hash.includes('#') ? location.hash.slice(1) : 'undefined-string-will-never-match';
I assume you mean `useLocation()` from `react-router-dom`, but I'm uncomfortable using it because the types are so horrible – `useLocation()` returns `any`, and therefore `useLocation().hash` is also any, how am I meant to know if I can trust it to always be a string, or whether it's going to be `undefined` or `null`?

2022-03-18 15:49 UTC, Morpheu5 commented on src/app/components/content/IsaacAccordion.tsx
> +                if ((section.id || "").includes(hashAnchor)) {
This *can't* be an equality though because a `section.id` might include a page id, IIRC. And in fact I'm testing with /concepts/prog_concepts_instructions#seq-instructions and it doesn't work if I check of equality: the `section.id` is indeed `prog_concepts_instructions|seq-instructions`.

2022-03-23 16:30 UTC, Morpheu5 commented on src/app/components/content/IsaacAccordion.tsx
> +                if ((section.id || "").includes(hashAnchor)) {
Uh, I forgot I ended up using `useLocation()` in the end, so marking this as resolved.

2022-03-28 10:06 UTC, mlt47 requested changes

2022-03-28 10:06 UTC, mlt47 commented on src/app/components/content/IsaacAccordion.tsx
> +                if ((section.id || "").includes(hashAnchor)) {
Ah right that is a good point about equality. `includes` is still "wrong" though, we should `split("|")` and grab the section's ID. It is also done in `Accordion.tsx` so we can pull the shared logic to a function in a service and reuse that.

2022-03-28 10:50 UTC, mlt47 approved these changes

2022-03-28 10:57 UTC, merged