Question confidence research gameboards
isaacphysics/isaac-react-app pull request #589
Opened 2022-06-20 17:06 UTC by chrisjpurdy

This does the following:
 - Implements confidence questions (pre and post) for arbitrary question types
 - Conditionally enables the use of these based on whether the gameboard is tagged with `CONFIDENCE_RESEARCH_BOARD` (option added to CS gameboard builder)
 - Record hint views on a question with confidence buttons as a log event with the tag `QUESTION_CONFIDENCE_HINT`, along with an id relating it to the current "confidence session"
 - Generates a new confidence session ID when "a new attempt is started" for a given question. This is different based on whether the question is a question or quick question:
   - Question: when the current attempt changes with the post-question being shown, or when the post-question is answered
   - Quick question: whenever the answer is hidden, or when the post-question is answered
 - Remove the confidence session ID, so data must be grouped by timestamp and user ID

Decent effort has been made to separate out the logic for confidence buttons as much as possible, so they can be easily modified in isolation, or removed completely if needed.
 
See the Google doc attached to the card for details on requirements for this change.

2022-06-27 09:41 UTC, mlt47 requested changes

2022-06-27 09:41 UTC, mlt47 commented on src/app/components/content/IsaacQuickQuestion.tsx
> +    const defaultOptions = () => <Row>
Why not make these functional components rather than functions that return JSX (even here within the other component)? Although they are not likely to be reused, it might be helpful for dev tools to record each layer of the react tree.

2022-06-27 09:41 UTC, mlt47 commented on src/app/components/elements/inputs/ConfidenceQuestions.tsx
> +            }
I'm not sure if we're benefitting much from doing this within Isaac. We will need to group log events chronologically during analysis outside of Isaac either way, i.e. to get information such as "was the next attempt correct". We could instead just send a flag into hint views or get hints components to check whether they are part of a research board to decide whether or not to also send the research hint view log event (maybe wrap it all up in a hook).
It doesn't do much harm to keep it in as long as we do at least think about whether or not we've got the correct groupings when we're doing the analysis. There may be unexpected behaviours like [Comparison](https://dl.acm.org/doi/10.1145/2876034.2893379), where students look at hints after getting the answer correct, that are interesting valid behaviours that we might miss by pre-emptive grouping of the log actions (I think Comparison would get caught with the session as it is, btw).

2022-06-27 09:57 UTC, mlt47 commented on src/app/components/elements/inputs/ConfidenceQuestions.tsx
> +                    answerCorrect: correct,
My local database is a little messed up for testing. I can't see how this can be the value after the response comes back from submitting the form and getting the attempt marked by the server?

2022-06-27 12:51 UTC, chrisjpurdy commented on src/app/components/elements/inputs/ConfidenceQuestions.tsx
> +                    answerCorrect: correct,
Yep this is definitely going to be the old answer - this was already here when I picked up the work so I assumed it just worked, my bad! I think I've got an idea to fix this, it might be a little hard to do though

2022-06-27 13:02 UTC, chrisjpurdy commented on src/app/components/elements/inputs/ConfidenceQuestions.tsx
> +            }
I've thought about the pairing of hints to previous attempts but its quite difficult as you would need two session IDs in use concurrently. 
WRT to the benefit of doing this, it makes comparing confidence pre and post feedback much easier - you can just merge entries with the same session ID, but this approach is only relevant to that specific research question.
I think you're right in that a single session identifier would be better to answer almost any other questions, and that the analysis can be done using timestamps within a single session for most questions and given a bit more work with scripting.

2022-06-27 17:49 UTC, chrisjpurdy commented on src/app/components/elements/inputs/ConfidenceQuestions.tsx
> +            }
On reflection I've removed the session ID all-together - it provides no benefit over a combined key of [day + user ID]. Maybe if it was much more sophisticated in what event are associated with each session then it would be better, but this is hard to do in a way that is flexible to answering every question.

2022-06-27 17:50 UTC, chrisjpurdy commented on src/app/components/elements/inputs/ConfidenceQuestions.tsx
> +                question: "Having read the feedback, how do you rate your confidence in answering this question again?",
I've asked Jane and Eirini to double check this and the following comment.

2022-06-28 07:15 UTC, mlt47 approved these changes

2022-06-28 07:15 UTC, mlt47 commented on src/app/components/content/IsaacQuestion.tsx
> +            {isCS && <ConfidenceContext.Provider value={{recordConfidence}}>
Rather than having two ConfidenceContext.Providers in this component, would there be a problem with just wrapping the IsaacQuestion component in one around the Form?

2022-06-28 07:15 UTC, mlt47 commented on src/app/components/elements/inputs/ConfidenceQuestions.tsx
> +        // that this log action will only run once for a given attempt.
This feels long-term fragile, but there isn't an easy alternative solution. Perhaps there exists an option using redux middleware where a state machine of sorts can make decisions based on which actions it sees and that might be a bit more explicit? Seeing as this feature is not fundamental to the use of Isaac, I don't think it's worth making the effort to rearchitect it yet.

2022-06-28 09:20 UTC, chrisjpurdy commented on src/app/components/content/IsaacQuestion.tsx
> +            {isCS && <ConfidenceContext.Provider value={{recordConfidence}}>
No problem at all - that's sorted 👍

2022-06-28 09:22 UTC, chrisjpurdy commented on src/app/components/elements/inputs/ConfidenceQuestions.tsx
> +        // that this log action will only run once for a given attempt.
I agree that it's fragile, but building a long term solution is a bit out of scope as you say, since this might be temporary and in any case is not a major part of Isaac.

2022-06-28 10:39 UTC, mlt47 approved these changes

2022-06-28 10:39 UTC, merged