Use `assignments/assign` to populate Set Assignments
isaacphysics/isaac-react-app pull request #610
Opened 2022-07-22 11:24 UTC by chrisjpurdy

Previously, the what-group-assigned-to-what-board info was stored in the `boards` state, which IMO wasn't right considering we have an `assignmentsByMe` state that we can reduce down to find this information.

The endpoint [removed in this PR](https://github.com/isaacphysics/isaac-api/pull/466) was being used to get the groups assigned to each gameboard individually, which was really inefficient and made one request for each gameboard you have. The way I've done it in this PR just requests all of the users set assignments (one that they have assigned) in one API request, and reduces it down in `O(number of assignments)` time to a map from gameboards to assigned groups.

2022-08-03 09:54 UTC, Morpheu5 requested changes
The code looks sensible enough, aside maybe from those confirmation boxes. I haven't tested this yet but it looks OK based on the changes.

EDIT: Tested, seems to work fine.

2022-08-03 11:37 UTC, chrisjpurdy commented on src/app/components/pages/SetAssignments.tsx
> +            deleteBoard(board.id, board.title);
Yeah the only reason why you don't need to dispatch this is because `deleteBoard` is being passed into the component via `dispatchToProps` using the Redux `connect` HOC pattern (see line 511 of this file). 

In the `dispatchToProps` argument of `connect` you specify an object containing action creators, and they get passed into the component already wrapped in a `dispatch` - the dispatch is still happening under the hood.

It's confusing here because the prop `deleteBoard` is shadowing the imported `deleteBoard` action creator.
Honestly, since we have access to `dispatch` via hooks, we shouldn't be using `connect` because it's a bit of an awkward pattern - all but ~4 components don't use it any more.

2022-08-03 11:39 UTC, chrisjpurdy commented on src/app/components/pages/MyGameboards.tsx
>          if (confirm(`Are you sure you want to remove '${board.title}' from your account?`)) {
I completely agree, it would probably be a different PR though since there are quite a few `confirm`s handling around 😵‍💫

2022-08-03 12:14 UTC, Morpheu5 commented on src/app/components/pages/MyGameboards.tsx
>          if (confirm(`Are you sure you want to remove '${board.title}' from your account?`)) {
Yes, we might as well make a separate card for that and go over the entire front-end.

2022-08-08 15:13 UTC, mlt47 approved these changes
The overall change looks sensible.

Be careful not to make the code look more complicated than it is by unnecessarily wrapping things in `useMemos`. We should only use them if we are quite certain that the computation is expensive or that we have evidence through profiling that it is beneficial. `useMemo` will have its own overhead (particularly on first computation) so it is not necessarily always a performance optimisation.

2022-08-09 08:35 UTC, chrisjpurdy commented on src/app/components/pages/SetAssignments.tsx
> +    const hasAssignedGroups = useMemo(() => assignees && assignees.length > 0, [assignees]);
Completely agree - I went though a phase of adding it to a bunch of places a week or so ago and then realised it wasn't a good idea after looking it up, I must have missed these!

2022-08-09 08:38 UTC, mlt47 commented on src/app/components/pages/SetAssignments.tsx
> +    const hasAssignedGroups = useMemo(() => assignees && assignees.length > 0, [assignees]);
```suggestion
    const assignmentLink = `/assignment/${board.id}`;
    const hasAssignedGroups = assignees && assignees.length > 0;
```

2022-08-09 08:50 UTC, mlt47 commented on src/app/components/pages/SetAssignments.tsx
> +    const hasAssignedGroups = useMemo(() => assignees && assignees.length > 0, [assignees]);
Might be an interesting project to build a version of react where there is an extra code generation step that makes every declaration immutable using immer, wraps all statements like this in useMemo, and then automatically figures out dependencies for all the hooks which need them. Would be interesting to see which use cases work better in that framework!

2022-08-09 08:51 UTC, merged