Only emphasise save button if account settings have changed
isaacphysics/isaac-react-app pull request #697
Opened 2023-01-24 10:37 UTC by chrisjpurdy

Uses `object-hash` to compare account settings object before and after. 

I fixed a few places where objects were being mutated, specifically `TrueFalseRadioInput` which was actually broken because of this.

2023-02-06 15:11 UTC, mlt47 requested changes
This will be a useful feature. A few small problems to fix first.

2023-02-07 10:55 UTC, chrisjpurdy commented on src/app/components/elements/panels/UserEmailPreferences.tsx
> -    const defaultEmailPreferences = {ASSIGNMENTS: true};
@mlt47 Personally I think this is the wrong place for the default, and really it should be set in the API when a user account is created. Setting it to the default after the first time they interact with their My Account email preferences tab seems nasty.

2023-02-07 11:42 UTC, chrisjpurdy commented on src/app/components/elements/inputs/TrueFalseRadioInput.tsx
> +export const TrueFalseRadioInput = ({id, stateObject, propertyName, setStateFunction, submissionAttempted, trueLabel="Yes", falseLabel="No"}: TrueFalseRadioProps<any>) => {
Ah that's annoying - I did add a bunch of optional element accesses to this component and others already but I must have missed this one!

2023-02-07 12:51 UTC, chrisjpurdy commented on src/app/components/elements/panels/UserEmailPreferences.tsx
> -    const defaultEmailPreferences = {ASSIGNMENTS: true};
(After discussing in the daily meet, I'll add this back in some form)

2023-02-07 12:53 UTC, chrisjpurdy commented on src/app/components/elements/inputs/SchoolInput.tsx
> +            setUserToUpdate?.({...userWithoutSchoolInfo, schoolOther: undefined, schoolId: undefined});
Not necessarily, because `userWithoutSchoolInfo` might contain `schoolOther` and `schoolId` attributes - I just wanted to make sure they were overwritten with `undefined` (and I can't use `delete` because that's mutation)

2023-02-07 15:41 UTC, chrisjpurdy commented on src/app/components/elements/panels/UserEmailPreferences.tsx
> -    const defaultEmailPreferences = {ASSIGNMENTS: true};
Done in most recent commit 👍

2023-02-07 15:47 UTC, chrisjpurdy commented on src/app/components/pages/MyAccount.tsx
>              (!userToUpdate.password || isNewPasswordConfirmed))
I've added the failure toast, but yeah there is probably a better way of dealing with this

2023-02-08 09:02 UTC, mlt47 commented on src/app/components/elements/inputs/SchoolInput.tsx
> +            setUserToUpdate?.({...userWithoutSchoolInfo, schoolOther: undefined, schoolId: undefined});
This PR has moved to using unpacking for the removal of `schoolId` and `schoolOther` in lines 63 and 51 rather than setting the values to `undefined` so we can use that for both methods.

2023-02-08 09:08 UTC, chrisjpurdy commented on src/app/components/elements/inputs/SchoolInput.tsx
> +            setUserToUpdate?.({...userWithoutSchoolInfo, schoolOther: undefined, schoolId: undefined});
Good point! I'll change it to that

2023-02-08 16:49 UTC, mlt47 approved these changes

2023-02-08 16:49 UTC, merged