Add assignment sorting dropdown to top of markbook/assignment progress page
isaacphysics/isaac-react-app pull request #735
Opened 2023-05-11 14:42 UTC by chrisjpurdy

Default sorting is now "start date descending", start date meaning the scheduled start date (if it exists - it is the creation date if not). 

Ascending and descending options exist for due date, start date, and title.

Isaac Physics:
 ![image](https://github.com/isaacphysics/isaac-react-app/assets/33040507/0e293172-5fb9-4a44-98f3-2ee383e29bd4)

Ada CS:
![image](https://github.com/isaacphysics/isaac-react-app/assets/33040507/d6ea3fc1-3813-420b-8ad9-8f9a556836e5)

2023-05-22 10:19 UTC, mlt47 requested changes

2023-05-22 10:19 UTC, mlt47 commented on src/app/state/slices/api/assignments.ts
> +                sortedAs = sortBy(as, a => a.gameboard?.title ?? a.quiz?.title ?? "");
https://github.com/isaacphysics/isaac-react-app/blob/7491cb1d0152ccfc8f01027c9bc87c61815f0bbe/src/app/services/gameboardBuilder.ts#L6
^ Is a nice function for sorting strings where numbers are sorted numerically, i.e. 10 > 2, through splitting the strings on spaces and decimal places. This title sort is a good candidate for reusing that function (as we saw from Lisa's example gameboards where weeks were enumerated).
The function should probably be moved and renamed so that we make more use of it.

2023-05-23 15:39 UTC, chrisjpurdy commented on src/app/state/slices/api/assignments.ts
> +    }, [sortOrder]);
Done 👍

2023-05-23 15:39 UTC, chrisjpurdy commented on src/app/state/slices/api/assignments.ts
> +                sortedAs = sortBy(as, a => a.gameboard?.title ?? a.quiz?.title ?? "");
I've moved and renamed it to `sortStringsNumerically` (wasn't really sure of the right name here)

2023-05-24 13:49 UTC, mlt47 approved these changes

2023-05-24 13:49 UTC, merged