Warn on duplicate group name
isaacphysics/isaac-react-app pull request #793
Opened 2023-09-13 08:19 UTC by jacbn

Will warn the user if they enter a group name when creating a new group or editing an existing one that already exists; this does not block them from adding it should they insist.

2023-09-13 10:55 UTC, mlt47 requested changes
It's looking good. I have some small suggestions.
We also talked about maybe showing a different feedback message if the group name matches an archived group name rather than matching an active group's name because matching an archived group name might be something that people are more likely to do on purpose.

2023-09-13 10:55 UTC, mlt47 commented on src/app/components/pages/Groups.tsx
> +                        valid={newGroupName !== undefined && newGroupName.length > 0 && !allGroups?.some(g => g.groupName == newGroupName)}
To avoid a little duplication and help with readability, I think here would be a good place to pull out this logic into a descriptively named variable (before the returned JSX).

```
const nameAlreadyInUse = isDefined(newGroupName) && newGroupName.length > 0 && allGroups?.some(g => g.groupName == newGroupName);
```
(There is also a useful utility function called `isDefined(...)`.)
The input can then have the props `invalid={nameAlreadyInUse} valid={!nameAlreadyInUse}`.


Or as it is logic shared across two components you could pull it out into a `function isNameAlreadyInUse(newGroupName, allGroups)`. As it is only this page that will need this functionality I would recommend keeping the function in this page (and module) rather than moving it into a service.

```
const nameAlreadyInUse = isNameAlreadyInUse(newGroupName, allGroups);
```

2023-09-13 10:55 UTC, mlt47 commented on src/app/components/pages/Groups.tsx
> +    const allGroups = [...(useGetGroupsQuery(false).currentData ?? []) , ...(useGetGroupsQuery(true).currentData ?? [])];
It's a shame that useGetGroupsQuery() doesn't have an option to return all groups. We could then filter them appropriately in the front-end code.
Perhaps we look at altering/fixing that endpoint as your first API PR.

However, before that, we can reduce the number of queries by one by doing something like:
```
const otherGroups = useGetGroupsQuery(!showArchived);

const allFroups = [...groups, ...(otherGroups.currentData ?? [])];
```

2023-09-13 15:09 UTC, jacbn commented on src/app/components/pages/Groups.tsx
> +                        valid={newGroupName !== undefined && newGroupName.length > 0 && !allGroups?.some(g => g.groupName == newGroupName)}
The group valid/invalid conditions are not quite opposites, as there is a third null state if the name is valid but has not changed. Otherwise agreed, changes made!

2023-09-14 09:27 UTC, mlt47 requested changes
Looking better and I'm quite sure the archived notification will be useful to users. Small tweak suggested.

2023-09-14 09:27 UTC, mlt47 commented on src/app/components/pages/Groups.tsx
> +                    <FormFeedback>A{isGroupNameInvalid && getNameConflictingGroup?.archived ? <>n archived</> : <></>} group with that name already exists.</FormFeedback>
I don't think you need the `isGroupNameInvalid &&` here because <FormFeedback> is by default only shown when the input group is invalid, but please correct me if I'm wrong.

2023-09-14 09:27 UTC, mlt47 commented on src/app/components/pages/Groups.tsx
> +    const getNameConflictingGroup = allGroups?.find(g => g.groupName == newGroupName && (isDefined(group) ? group.id != g.id : true));
`find`-ing the conflicting group to check the archived status later is neat though :)

2023-09-15 09:03 UTC, jacbn commented on src/app/components/pages/Groups.tsx
> +    const getNameConflictingGroup = allGroups?.find(g => g.groupName == newGroupName && (isDefined(group) ? group.id != g.id : true));
Good spot, this was a function the first time I wrote it, hence the name.

2023-09-15 09:03 UTC, jacbn commented on src/app/components/pages/Groups.tsx
> +                    <FormFeedback>A{isGroupNameInvalid && getNameConflictingGroup?.archived ? <>n archived</> : <></>} group with that name already exists.</FormFeedback>
Seems to work without, you're right. Good to know!

2023-09-19 08:22 UTC, mlt47 approved these changes
🙌

2023-09-19 08:22 UTC, merged