Undo gameboard question deletion
isaacphysics/isaac-react-app pull request #796
Opened 2023-09-15 16:46 UTC by jacbn

Adds undo and redo buttons to gameboard editing for easier workflow.

Just the undo was requested, but it's then equally easy to make mistakes using that, so a redo was added too.

2023-09-18 13:27 UTC, jsharkey13 commented on src/app/components/elements/GameboardBuilderRow.tsx
> +    {provided, snapshot, question, selectedQuestions, setSelectedQuestions, questionOrder, setQuestionOrder, previousQuestionOrderStack: previousQuestionOrderStack, setPreviousQuestionOrderStack: set
Aside from the length of this line, do you need to be explicit in the mapping here? Most of the rest use the shorthand, and one of the five params you have added does too, but the rest do not despite looking to be mapping to the same name?

2023-09-18 13:27 UTC, jsharkey13 commented on src/app/components/elements/modals/QuestionSearchModal.tsx
> +export const QuestionSearchModal = ({originalSelectedQuestions, setOriginalSelectedQuestions, originalQuestionOrder, setOriginalQuestionOrder, previousQuestionOrder: previousQuestionOrderStack, setPr
Ditto here regarding the mix of explicit vs implicit mappings?

2023-09-18 13:27 UTC, jsharkey13 commented on src/app/components/pages/GameboardBuilder.tsx
> +    const resetRedoStacks = () => {setRedoQuestionOrderStack([]); setRedoSelectedQuestionsStack([]);}
This function should probably come after all the hooks, and be on several lines so that the semicolon mess looks clearer!

2023-09-18 14:24 UTC, jacbn commented on src/app/components/elements/GameboardBuilderRow.tsx
> +    {provided, snapshot, question, selectedQuestions, setSelectedQuestions, questionOrder, setQuestionOrder, previousQuestionOrderStack: previousQuestionOrderStack, setPreviousQuestionOrderStack: set
This is a VSC config option, good spot. `typescript.preferences.useAliasesForRenames` is now false :)

2023-09-18 15:09 UTC, jacbn commented on src/app/components/pages/GameboardBuilder.tsx
> +                                                                }}
The redo stack is limited in size by the undo stack, so don't need to check size

2023-09-20 09:32 UTC, mlt47 requested changes
This seems to function well (although perhaps the stack length of 9 is not being enforced due to multiple `setStates(...)` in a render).
I've included some suggestions.

We might also want to investigate creating a custom hook to wrap some of this logic in one place and expose a reduced API to the components. This will likely require also looking at how the `useContext()` hook works.

2023-09-20 09:32 UTC, mlt47 commented on src/app/components/elements/GameboardBuilderRow.tsx
> +                        }
In this section `setPreviousQuestionOrderStack(...)` is called multiple times, but `setState(...)` does not update `previousQuestionOrderStack` immediately, it updates it at the end of the render ready for the next "snapshot" so (I think) it will take the last value each time.
It is possible to fix this by rearranging the logic or using an "updater function": https://react.dev/reference/react/useState#updating-state-based-on-the-previous-state

2023-09-20 09:32 UTC, mlt47 commented on src/app/components/pages/GameboardBuilder.tsx
> +                                                                color="primary" outline
Perhaps have a play around with the style. Currently undo and redo are emphasised as much as the add questions button. `/gameboards/new`'s "Shuffle questions" might be a good example to try and copy (`btn-sm`). If there are appropriate icons that might look better included on the buttons too.

2023-09-22 16:28 UTC, mlt47 approved these changes
This feature has quite a lot of logic involved in getting it working.
Works well, the buttons look a lot better now and the code is improved with the refactor.

2023-09-22 16:28 UTC, merged