Add filters to the "Manage Tests" page
isaacphysics/isaac-react-app pull request #828
Opened 2023-10-20 13:49 UTC by jacbn

Adds title, group, and date filtering to the Manage Tests page.

Ideally once the ability to set tests to multiple groups at once is in place, cards in this page could be grouped in a similar way.

2023-10-20 13:53 UTC, jacbn commented on src/scss/phy/quiz.scss
> +  transform: translateY(3px);
I'm not convinced this is the best way to do this, if there are any other suggestions. Text inside buttons in Isaac have different heights to those in Ada -- this does alleviate the problem, but forcing it down feels a little ugly.

2023-10-27 08:59 UTC, mlt47 requested changes
This works well.
I would suggest changing it to work responsively and then sending a screenshot to the content teams to check that they approve (as they did not specifically ask for this and they might want to add/alter documentation).

2023-10-27 08:59 UTC, mlt47 commented on src/app/components/pages/quizzes/SetQuizzes.tsx
> +                    {showFilters && <RS.Row>
Once opened, the filters are not responsive to screen size changes. I think we would want these to be accessible to mobile too. Anecdotally, teachers do sometimes do classroom management tasks on mobile devices - on their commute, for example.

2023-10-27 08:59 UTC, mlt47 commented on src/app/components/pages/quizzes/SetQuizzes.tsx
> +                                }
Some shared filter code here that could be lifted out into a function.

2023-11-01 14:46 UTC, mlt47 approved these changes

2023-11-02 09:16 UTC, merged