Test setting to multiple groups
isaacphysics/isaac-react-app pull request #830
Opened 2023-10-25 11:28 UTC by skyepurchase

Relies on [Test setting to multiple groups #564](https://github.com/isaacphysics/isaac-api/pull/564) in the backend as it anticipates the new POST and return types.

Single quiz assignments are still possible by selecting only one group.

2023-10-30 16:49 UTC, mlt47 reviewed
A few small comments and maybe a few separate tasks for the future but I'm happy with this.

2023-10-30 16:49 UTC, mlt47 commented on src/app/components/elements/modals/QuizSettingModal.tsx
> +    const [feedbackMode, setFeedbackMode] = useState<QuizFeedbackMode>();
Is there a reason we're dropping the ability to set the initial feedback mode? I see that we're not making use of it so far but neither are we making use of the initialScheduledStartDate or initialDueDate.

2023-10-30 16:49 UTC, mlt47 commented on src/app/services/quiz.ts
> +        const isScheduled = scheduledStartDate !== undefined;
I see we perform similar validation when setting bulk assignments and that is, correctly, the most similar part of code to copy. However, I'm not entirely convinced we should be doing validation of this sort in the action dispatching thunk. We have this validation logic in the back-end, where it matters, and we also have this logic encoded in the form in the front-end, for a more responsive user experience. I think that having the validation logic here again doesn't gain us anything except increasing the chance of introducing bugs when duplicated logic is not updated consistently in all places.
Let's not do it as part of this PR, but I would suggest creating a separate card to remove this validation logic for both quizzes and assignments. It might even mean we can replace the createAsyncThunk with more standard RTK Query data fetching (but that might not be possible). What do you think?

2023-10-30 16:49 UTC, mlt47 commented on src/app/state/slices/api/quizApi.ts
> +        assignQuiz: build.mutation<AssignmentFeedbackDTO[], QuizAssignmentDTO[]>({
It is confusing (and obviously not your fault!) that the name AssignmentFeedbackDTO does not match the back-end's name for the same data transfer object, AssignmentStatusDTO. I would recommend altering one or the other so that they match again, but this can be a separate card on Trello.

2023-10-31 09:51 UTC, skyepurchase commented on src/app/components/elements/modals/QuizSettingModal.tsx
> +    const [feedbackMode, setFeedbackMode] = useState<QuizFeedbackMode>();
At one stage I had swapped these to being `undefined` rather than `null` which didn't work and I must have forgotten to reset feedback mode correctly. Will change this back

2023-10-31 09:54 UTC, skyepurchase commented on src/app/services/quiz.ts
> +        const isScheduled = scheduledStartDate !== undefined;
I think a separate card would be good. Would be something to discuss, but I agree that there are a lot of places where the same check/group of checks are done where they are not necessarily required.

2023-10-31 11:47 UTC, skyepurchase commented on src/app/state/slices/api/quizApi.ts
> +        assignQuiz: build.mutation<AssignmentFeedbackDTO[], QuizAssignmentDTO[]>({
Card created

2023-11-01 17:07 UTC, mlt47 requested changes
Tiny label tweak recommendation.

2023-11-01 17:07 UTC, mlt47 commented on src/app/components/elements/modals/QuizSettingModal.tsx
> +                    return <StyledSelect isMulti placeholder="Select groups"
Sorry, what I meant by the label needing updating was the value in line 97 rather than the placeholder. "None" for the placeholder is fine (if a bit "techy") as it matches the group(s) input for setting assignments.

2023-11-02 10:04 UTC, mlt47 approved these changes

2023-11-02 10:07 UTC, merged