Use carets for sort indicators
isaacphysics/isaac-react-app pull request #880
Opened 2024-01-15 15:16 UTC by skyepurchase

2024-01-15 17:15 UTC, skyepurchase commented
Would be an idea to make the `boardOrder` into two separate variables, one that tracks the column and one that tracks the order (forward or reverse). This would affect setQuizzes pages which are currently being changed and so that change would need to wait.

2024-01-17 16:11 UTC, mlt47 requested changes
I much prefer these sort indicators :).

I have made some suggestions.

We might also want to experiment with altering the Physics table to be bordered if it is not clear which column label is associated with which sort button.

2024-01-17 16:11 UTC, mlt47 commented on src/app/components/pages/MyGameboards.tsx
> +    }
As there's so much duplication between this and the sort item in the AdaTable, I would recommend pulling it out into a separate component. As well as being neater it reduces the chance of bugs when one is updated but not the other.

2024-01-17 16:11 UTC, mlt47 commented on src/app/components/pages/MyGameboards.tsx
> +        const sortArrows = <button className="sort physics" onClick={() => {toggleSort(itemOrder, reverseOrder);}}>
So that the button is given the space it needs in the table cell when being rendered, I would recommend changing this from being `position: absolute` to `position: relative`. It will then require a bit more CSS tweaking to get the correct positioning.

2024-01-18 17:08 UTC, skyepurchase commented on src/app/components/pages/MyGameboards.tsx
> +        const sortArrows = <button className="sort physics" onClick={() => {toggleSort(itemOrder, reverseOrder);}}>
This change meant that Ada and Physics are the same. There was weird text-alignment for Ada where the table header had `vertical-align: bottom` but I couldn't find that being set anywhere, I added `vertical-align: middle` to keep the alignment consistent across tables.

2024-01-22 16:13 UTC, mlt47 requested changes

2024-01-22 16:13 UTC, mlt47 commented on src/scss/common/pages.scss
> +    th {
The alignment and positioning of the table header text and sort buttons doesn't look correct in my browser.

2024-01-22 16:53 UTC, jsharkey13 commented on src/app/components/pages/SetAssignments.tsx
> +import { sortItem } from "./MyGameboards";
(I dislike the `index.ts` approach unless it is unavoidable since it prevents tree-shaking and bundle splitting for anything which then imports it. Making a smaller new component/element as suggested feels cleaner and avoid this).

2024-01-23 12:16 UTC, skyepurchase commented on src/scss/common/pages.scss
> +    th {
It appears that Firefox was aligning the two elements (the text and the buttons) differently compared to Chrome and Edge. Wrapping it in a div to align the items within the div works consistently across browsers

2024-01-24 17:22 UTC, mlt47 commented on src/app/components/pages/MyGameboards.tsx
> +        <SortItemHeader key={"completion"} itemOrder={BoardOrder.completion} reverseOrder={BoardOrder["-completion"]} boardOrder={boardOrder} setBoardOrder={setBoardOrder}>
We only need `key`s when we're generating a list of components (i.e. using a map where the order could change between renders). Here we are declaratively setting out the components so it is not necessary.

2024-01-24 17:25 UTC, mlt47 commented on src/app/components/pages/MyGameboards.tsx
> +    const tableHeader = <tr className="my-gameboard-table-header">
The col widths on Ada seem to be incorrect on this table, but also worth checking the others.

2024-01-30 16:33 UTC, skyepurchase commented on src/app/components/pages/MyGameboards.tsx
> +    const tableHeader = <tr className="my-gameboard-table-header">
With the additional merge conflict from the changes to Stages and Difficulties on Physics this was dealt with but not very obviously

2024-02-06 09:17 UTC, mlt47 approved these changes
Works well and the code looks like an idiomatic React solution to the sharing of code which is great.

2024-02-06 09:17 UTC, merged