Adding expansion animation to Physics
isaacphysics/isaac-react-app pull request #889
Opened 2024-01-22 17:30 UTC by skyepurchase

- Add expansion animation to Physics reorder questions
- Prevent validation banner overflowing card
- Fix ESLint warnings

2024-01-23 15:50 UTC, mlt47 requested changes
Requested some small changes to neaten the codebase. However it's worth considering the quiz/test case where these expanded questions are not in accordions and so the animation is less clear/not visible unless the expanded question is the first question in the quiz section.

2024-01-23 15:50 UTC, mlt47 commented on src/scss/phy/questions.scss
> +  .question-component:not(.isaacReorderQuestion) {
Because isaacReorderQuestions are basically the same as isaacParsonsQuestions, won't these style rules need to be applied when the question component is not either?

2024-01-23 16:12 UTC, skyepurchase commented on src/scss/phy/questions.scss
> +  .question-component:not(.isaacReorderQuestion) {
Looking at the content base there are no isaacParsonsQuestions on Physics so changed this over. Having both is probably best though, you're right

2024-01-24 17:35 UTC, merged

2024-01-24 17:37 UTC, mlt47 reviewed
Looks good and the functional component looks like a good idiomatic solution.